const COLORS={blue:'#2563EB',blue2:'#60A5FA',teal:'#0D9488',teal2:'#2DD4BF',rose:'#E11D48',slate:'#64748B',grid:'#E8EEF5'};
const FILES={monthly:'mart_marketplace_monthly.csv',categories:'mart_category_performance.csv',geography:'mart_geography_performance.csv',delivery:'delivery_performance.csv',concentration:'seller_concentration.csv',activation:'activation_summary.csv',segmentation:'seller_segmentation.csv',stats:'statistical_validation.csv'};
const D={};const charts=[];const CUTOFF='2018-08';
function parseCSV(text){text=text.replace(/^\uFEFF/,'');const rows=[];let row=[],field='',q=false;for(let i=0;i<text.length;i++){const c=text[i],nxt=text[i+1];if(c==='"'){if(q&&nxt==='"'){field+='"';i++;}else q=!q;}else if(c===','&&!q){row.push(field);field='';}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&nxt==='\n')i++;row.push(field);field='';if(row.some(v=>v!==''))rows.push(row);row=[];}else field+=c;}if(field||row.length){row.push(field);rows.push(row);}if(rows.length<2)return[];const h=rows[0].map(x=>x.trim());return rows.slice(1).map(r=>Object.fromEntries(h.map((k,i)=>[k,(r[i]??'').trim()])))}
const n=v=>{const x=Number(v);return Number.isFinite(x)?x:0};const sum=(a,f)=>a.reduce((s,x)=>s+n(f(x)),0);const pct=(v,d=1)=>`${(n(v)*100).toFixed(d)}%`;const moneyM=v=>`R$ ${(n(v)/1e6).toFixed(2)}M`;const money=v=>`R$ ${new Intl.NumberFormat('en-US',{maximumFractionDigits:2}).format(n(v))}`;const compact=v=>new Intl.NumberFormat('en-US',{notation:'compact',maximumFractionDigits:1}).format(n(v));const titleCase=s=>String(s||'').replaceAll('_',' ').replace(/\b\w/g,m=>m.toUpperCase());
function group(arr,key){return arr.reduce((m,x)=>{const k=x[key];(m[k]??=[]).push(x);return m},{})}
function gini(values){const a=values.map(n).filter(v=>v>0).sort((a,b)=>a-b),N=a.length,S=a.reduce((x,y)=>x+y,0);if(!N||!S)return 0;let num=0;a.forEach((v,i)=>num+=(2*(i+1)-N-1)*v);return num/(N*S)}
function delta(curr,prev,invert=false,ppMode=false){if(!prev)return{txt:'—',tone:'neutral'};const d=ppMode?(curr-prev)*100:(curr-prev)/Math.abs(prev);const good=invert?d<0:d>0;return{txt:`${d>=0?'▲':'▼'} ${ppMode?`${d>=0?'+':''}${d.toFixed(1)} p.p.`:`${d>=0?'+':''}${(d*100).toFixed(1)}%`}`,tone:good?'pos':d===0?'neutral':'neg'}}
function axis(){return{axisLine:{lineStyle:{color:'#CBD5E1'}},axisTick:{show:false},axisLabel:{color:'#64748B',fontSize:9},splitLine:{lineStyle:{color:COLORS.grid}}}}
function tooltip(){return{trigger:'axis',backgroundColor:'#0F172A',borderWidth:0,textStyle:{fontSize:10},padding:9}}
function ec(id,opt){const el=document.getElementById(id);if(!el)return;const c=echarts.init(el);c.setOption(opt);charts.push(c);return c}
function spark(id,vals,color,fill){ec(id,{animation:false,grid:{left:0,right:0,top:2,bottom:0},xAxis:{type:'category',show:false,data:vals.map((_,i)=>i)},yAxis:{type:'value',show:false,scale:true},series:[{type:'line',data:vals,symbol:'none',smooth:.3,lineStyle:{color,width:1.6},areaStyle:{color:fill,opacity:.7}}]})}
function kpi(label,value,color,icon,d,sparkId){return `<div class="kpi"><div class="kpi-label">${label}</div><div class="kpi-value" style="color:${color}">${value}</div><div class="kpi-icon" style="color:${color};background:${color}14">${icon}</div><div class="kpi-bottom"><div class="delta ${d.tone}">${d.txt}<small>vs. previous period</small></div><div id="${sparkId}" class="spark"></div></div></div>`}
function insight(icon,title,text,tone){return `<div class="insight"><div class="insight-icon tone-${tone}">${icon}</div><div><b>${title}</b><p>${text}</p></div></div>`}
function highlight(value,label,color){return `<div class="highlight" style="--accent:${color}"><strong>${value}</strong><span>${label}</span></div>`}
function heat(v,max){const t=Math.max(0,Math.min(1,max?v/max:0));const light=[239,246,255],dark=[37,99,235];const rgb=light.map((x,i)=>Math.round(x+(dark[i]-x)*t));const fg=t>.62?'#fff':'#0F172A';return `background:rgb(${rgb.join(',')});color:${fg}`}
async function load(){try{await Promise.all(Object.entries(FILES).map(async([k,f])=>{const r=await fetch(`data/${f}`);if(!r.ok)throw new Error(`${f}: ${r.status}`);D[k]=parseCSV(await r.text())}));D.monthly=D.monthly.filter(x=>x.purchase_month<=CUTOFF).sort((a,b)=>a.purchase_month.localeCompare(b.purchase_month));D.categories=D.categories.filter(x=>x.purchase_month<=CUTOFF);initFilters();render();document.getElementById('loading').classList.add('hidden')}catch(e){document.getElementById('loading').classList.add('hidden');const b=document.getElementById('errorBox');b.hidden=false;b.textContent=`Could not load dashboard data: ${e.message}`;console.error(e)}}
function initFilters(){const m=document.getElementById('monthFilter'),c=document.getElementById('categoryFilter'),s=document.getElementById('stateFilter');m.innerHTML=`<option value="all">All periods</option>`+D.monthly.map(x=>`<option>${x.purchase_month}</option>`).join('');const cats=[...new Set(D.categories.map(x=>x.product_category_name_english))].sort();c.innerHTML=`<option value="all">All categories</option>`+cats.map(x=>`<option value="${x}">${titleCase(x)}</option>`).join('');s.innerHTML=`<option value="all">All states</option>`+D.geography.map(x=>`<option>${x.seller_state}</option>`).join('');[m,c,s].forEach(el=>el.onchange=render);document.getElementById('resetFilters').onclick=()=>{m.value='all';c.value='all';s.value='all';render()}}
function selectedMonthly(){const sel=document.getElementById('monthFilter').value;if(sel==='all')return D.monthly;return D.monthly.filter(x=>x.purchase_month<=sel)}
function categoryRows(){const month=document.getElementById('monthFilter').value,sel=document.getElementById('categoryFilter').value;let a=D.categories;if(month!=='all')a=a.filter(x=>x.purchase_month===month);const agg=Object.entries(group(a,'product_category_name_english')).map(([k,v])=>({name:k,gmv:sum(v,x=>x.gmv_proxy)})).sort((a,b)=>b.gmv-a.gmv);if(sel==='all')return agg.slice(0,5);const chosen=agg.find(x=>x.name===sel);return [chosen,...agg.filter(x=>x.name!==sel).slice(0,4)].filter(Boolean)}
function stateRows(){const sel=document.getElementById('stateFilter').value;const all=D.geography.map(x=>({state:x.seller_state,gmv:n(x.gmv_proxy),orders:n(x.orders),sellers:n(x.active_sellers),share:n(x.gmv_share)})).sort((a,b)=>b.gmv-a.gmv);if(sel==='all')return all.slice(0,5);const chosen=all.find(x=>x.state===sel);return [chosen,...all.filter(x=>x.state!==sel).slice(0,4)].filter(Boolean)}
function render(){charts.splice(0).forEach(c=>{try{c.dispose()}catch{}});const monthly=selectedMonthly(),last=monthly.at(-1),prev=monthly.at(-2)||last;const allMode=document.getElementById('monthFilter').value==='all';const totalGmv=allMode?sum(monthly,x=>x.gmv_proxy):n(last.gmv_proxy);const totalOrders=allMode?sum(monthly,x=>x.orders):n(last.orders);const sellers=allMode?sum(D.geography,x=>x.active_sellers):n(last.active_sellers);const aov=totalOrders?totalGmv/totalOrders:0;const lateRate=allMode?n(D.delivery.find(x=>x.delivery_bucket==='late')?.order_share):n(last.late_delivery_rate);const dG=delta(n(last.gmv_proxy),n(prev.gmv_proxy)),dO=delta(n(last.orders),n(prev.orders)),dS=delta(n(last.active_sellers),n(prev.active_sellers)),dA=delta(n(last.aov),n(prev.aov)),dL=delta(n(last.late_delivery_rate),n(prev.late_delivery_rate),true,true);document.getElementById('kpiGrid').innerHTML=kpi('GMV (R$M)',moneyM(totalGmv),COLORS.blue,'▥',dG,'spG')+kpi('Orders (K)',compact(totalOrders),COLORS.teal,'🛒',dO,'spO')+kpi('Active Sellers',compact(sellers),COLORS.blue,'♟',dS,'spS')+kpi('Avg Order Value (R$)',money(aov),COLORS.teal,'◉',dA,'spA')+kpi('Late Delivery Rate',pct(lateRate),COLORS.rose,'🚚',dL,'spL');const recent=monthly.slice(-10);spark('spG',recent.map(x=>n(x.gmv_proxy)),COLORS.blue,'#DBEAFE');spark('spO',recent.map(x=>n(x.orders)),COLORS.teal,'#CCFBF1');spark('spS',recent.map(x=>n(x.active_sellers)),COLORS.blue2,'#DBEAFE');spark('spA',recent.map(x=>n(x.aov)),COLORS.teal2,'#CCFBF1');spark('spL',recent.map(x=>n(x.late_delivery_rate)),COLORS.rose,'#FFE4E6');renderTrend(monthly);renderConcentration();renderCategories();renderStates();renderMatrix();renderNarrative(lateRate,sellers,last)}
function renderTrend(monthly){const a=monthly.filter(x=>n(x.orders)>=50);ec('trendChart',{tooltip:tooltip(),legend:{top:0,left:0,itemWidth:9,itemHeight:9,textStyle:{fontSize:8,color:'#475569'},data:['GMV Proxy (R$M)','Orders (K)']},grid:{left:50,right:48,top:35,bottom:40},xAxis:{...axis(),type:'category',data:a.map(x=>x.purchase_month),axisLabel:{color:'#64748B',fontSize:8,formatter:v=>v.replace('-','\n')}},yAxis:[{...axis(),type:'value',name:'GMV (R$M)',nameTextStyle:{fontSize:8,color:'#64748B'},axisLabel:{formatter:v=>`${(v/1e6).toFixed(1)}`,fontSize:8}},{...axis(),type:'value',name:'Orders (K)',nameTextStyle:{fontSize:8,color:COLORS.teal},axisLabel:{formatter:v=>`${(v/1000).toFixed(0)}`,color:COLORS.teal,fontSize:8}}],series:[{name:'GMV Proxy (R$M)',type:'bar',data:a.map(x=>n(x.gmv_proxy)),itemStyle:{color:COLORS.blue,borderRadius:[2,2,0,0]}},{name:'Orders (K)',type:'line',yAxisIndex:1,data:a.map(x=>n(x.orders)),smooth:.25,symbol:'none',lineStyle:{color:COLORS.teal,width:2.3},itemStyle:{color:COLORS.teal}}]})}
function renderConcentration(){const rows=[...D.concentration].sort((a,b)=>n(a.top_seller_share)-n(b.top_seller_share));const anchors=[[0,0],...rows.slice().reverse().map(r=>[1-n(r.top_seller_share),1-n(r.gmv_proxy_share)]),[1,1]].sort((a,b)=>a[0]-b[0]);ec('lorenzChart',{tooltip:{trigger:'axis',formatter:p=>`${pct(p[0].value[0])} of sellers<br/>${pct(p[0].value[1])} of GMV`},legend:{top:0,left:0,itemWidth:9,itemHeight:9,textStyle:{fontSize:8,color:'#475569'},data:['Observed curve','Line of Equality']},grid:{left:46,right:16,top:34,bottom:30},xAxis:{...axis(),type:'value',min:0,max:1,axisLabel:{formatter:v=>`${Math.round(v*100)}%`,fontSize:8}},yAxis:{...axis(),type:'value',min:0,max:1,axisLabel:{formatter:v=>`${Math.round(v*100)}%`,fontSize:8}},series:[{name:'Observed curve',type:'line',data:anchors,symbol:'none',smooth:.35,lineStyle:{color:COLORS.blue,width:3}},{name:'Line of Equality',type:'line',data:[[0,0],[1,1]],symbol:'none',lineStyle:{color:'#94A3B8',width:1.2,type:'dashed'}}]});const gv=gini(D.segmentation.map(x=>x.total_gmv_proxy));document.getElementById('giniValue').textContent=gv.toFixed(3);const t20=D.concentration.find(x=>Math.abs(n(x.top_seller_share)-.2)<.0001);document.getElementById('top20Value').textContent=pct(t20?.gmv_proxy_share)}
function renderCategories(){const rows=categoryRows(),colors=['#2563EB','#3B82F6','#60A5FA','#93C5FD','#BFDBFE'];ec('categoryChart',{grid:{left:90,right:50,top:10,bottom:20},xAxis:{...axis(),type:'value',axisLabel:{formatter:v=>`R$${(v/1e6).toFixed(1)}M`,fontSize:7}},yAxis:{...axis(),type:'category',inverse:true,data:rows.map(x=>titleCase(x.name)),axisLabel:{fontSize:7,width:78,overflow:'truncate'}},series:[{type:'bar',data:rows.map((x,i)=>({value:x.gmv,itemStyle:{color:colors[i]},label:{show:true,position:'right',formatter:p=>moneyM(p.value),fontSize:7}}))}]})}
function renderStates(){const rows=stateRows(),colors=['#0F766E','#0D9488','#14B8A6','#2DD4BF','#5EEAD4'];ec('stateChart',{grid:{left:40,right:58,top:10,bottom:20},xAxis:{...axis(),type:'value',axisLabel:{formatter:v=>`R$${(v/1e6).toFixed(0)}M`,fontSize:7}},yAxis:{...axis(),type:'category',inverse:true,data:rows.map(x=>x.state),axisLabel:{fontSize:8}},series:[{type:'bar',data:rows.map((x,i)=>({value:x.gmv,itemStyle:{color:colors[i]},label:{show:true,position:'right',formatter:p=>moneyM(p.value),fontSize:7}}))}]})}
function renderMatrix(){const rows=stateRows(),maxShare=Math.max(...rows.map(x=>x.share)),maxGmv=Math.max(...rows.map(x=>x.gmv)),maxSellers=Math.max(...rows.map(x=>x.sellers));document.getElementById('stateTable').innerHTML=`<thead><tr><th>State</th><th class="num">Active Sellers</th><th class="num">State GMV</th><th class="num">GMV Share</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r.state}</td><td class="num heat" style="${heat(r.sellers,maxSellers)}">${r.sellers.toLocaleString()}</td><td class="num heat" style="${heat(r.gmv,maxGmv)}">${money(r.gmv)}</td><td class="num heat" style="${heat(r.share,maxShare)}">${pct(r.share)}</td></tr>`).join('')}<tr class="total"><td>Total</td><td></td><td class="num">${money(sum(rows,x=>x.gmv))}</td><td></td></tr></tbody>`}
function renderNarrative(lateRate,sellers,last){const top20=n(D.concentration.find(x=>Math.abs(n(x.top_seller_share)-.2)<.0001)?.gmv_proxy_share),act=D.activation[0]||{},review=D.stats.find(x=>x.test==='late_delivery_vs_review_score'),gap=n(review?.effect_size),g=gini(D.segmentation.map(x=>x.total_gmv_proxy));document.getElementById('insights').innerHTML=insight('↗','Marketplace Momentum',`Latest complete month: ${moneyM(last.gmv_proxy)} GMV and ${compact(last.orders)} orders.`,'teal')+insight('◉','High Concentration',`Top 20% of sellers contribute ${pct(top20)} of GMV.`,'blue')+insight('!','Operational Risk',`Late delivery is ${pct(lateRate)}; late orders have a ${gap.toFixed(2)}-point review gap.`,'rose')+insight('♟','Large Seller Base',`${sellers.toLocaleString()} active sellers are observed across seller states.`,'blue');document.getElementById('highlights').innerHTML=highlight(g.toFixed(3),'Seller Gini',COLORS.blue)+highlight(pct(top20),'Top 20% Seller Share',COLORS.blue)+highlight(pct(act.activation_rate_le_30d),'30D Activation',COLORS.teal)+highlight(pct(act.activation_rate_le_90d),'90D Activation','#0F766E')+highlight(`${gap.toFixed(2)} pts`,'Review Gap',COLORS.rose)}
window.addEventListener('resize',()=>charts.forEach(c=>{try{c.resize()}catch{}}));load();
