const COLORS={blue:'#2563EB',blue2:'#60A5FA',teal:'#0D9488',teal2:'#2DD4BF',rose:'#E11D48',slate:'#64748B',grid:'#E8EEF5'};
const FILES={monthly:'mart_marketplace_monthly.csv',categories:'category_analysis_extended.csv',geography:'mart_geography_performance.csv',delivery:'delivery_performance.csv',concentration:'seller_concentration.csv',activation:'activation_summary.csv',stats:'statistical_validation.csv',completeness:'period_completeness.csv',headline:'headline_metrics.json'};
const D={};const charts=[];
function parseCSV(text){text=text.replace(/^\uFEFF/,'');const rows=[];let row=[],field='',q=false;for(let i=0;i<text.length;i++){const c=text[i],nxt=text[i+1];if(c==='"'){if(q&&nxt==='"'){field+='"';i++;}else q=!q;}else if(c===','&&!q){row.push(field);field='';}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&nxt==='\n')i++;row.push(field);field='';if(row.some(v=>v!==''))rows.push(row);row=[];}else field+=c;}if(field||row.length){row.push(field);rows.push(row);}if(rows.length<2)return[];const h=rows[0].map(x=>x.trim());return rows.slice(1).map(r=>Object.fromEntries(h.map((k,i)=>[k,(r[i]??'').trim()])));}
const n=v=>{const x=Number(v);return Number.isFinite(x)?x:0};
const maybe=v=>{if(v===null||v===undefined||v==='')return null;const x=Number(v);return Number.isFinite(x)?x:null};
const sum=(a,f)=>a.reduce((s,x)=>s+n(f(x)),0);
const pct=v=>v===null||v===undefined?'N/A':`${(n(v)*100).toFixed(1)}%`;
const moneyM=v=>`R$ ${(n(v)/1e6).toFixed(2)}M`;
const money=v=>`R$ ${new Intl.NumberFormat('en-US',{maximumFractionDigits:2}).format(n(v))}`;
const compact=v=>new Intl.NumberFormat('en-US',{notation:'compact',maximumFractionDigits:1}).format(n(v));
const titleCase=s=>String(s||'').replaceAll('_',' ').replace(/\b\w/g,m=>m.toUpperCase());
function delta(curr,prev,invert=false,ppMode=false){if(curr===null||prev===null||prev===undefined||prev===0)return{txt:'N/A',tone:'neutral'};const d=ppMode?(curr-prev)*100:(curr-prev)/Math.abs(prev);const good=invert?d<0:d>0;return{txt:`${d>=0?'▲':'▼'} ${ppMode?`${d>=0?'+':''}${d.toFixed(1)} p.p.`:`${d>=0?'+':''}${(d*100).toFixed(1)}%`}`,tone:good?'pos':d===0?'neutral':'neg'};}
function axis(){return{axisLine:{lineStyle:{color:'#CBD5E1'}},axisTick:{show:false},axisLabel:{color:'#64748B',fontSize:9},splitLine:{lineStyle:{color:COLORS.grid}}};}
function tooltip(){return{trigger:'axis',backgroundColor:'#0F172A',borderWidth:0,textStyle:{fontSize:10},padding:9};}
function ec(id,opt){const el=document.getElementById(id);if(!el)return;const c=echarts.init(el);c.setOption(opt);charts.push(c);return c;}
function spark(id,vals,color,fill){const clean=vals.filter(v=>v!==null&&Number.isFinite(v));const el=document.getElementById(id);if(!el)return;if(clean.length<2){el.innerHTML='<span style="font-size:9px;color:#94A3B8">N/A</span>';return;}ec(id,{animation:false,grid:{left:0,right:0,top:2,bottom:0},xAxis:{type:'category',show:false,data:clean.map((_,i)=>i)},yAxis:{type:'value',show:false,scale:true},series:[{type:'line',data:clean,symbol:'none',smooth:.25,lineStyle:{color,width:1.6},areaStyle:{color:fill,opacity:.7}}]});}
function kpi(label,value,color,icon,d,sparkId){return `<div class="kpi"><div class="kpi-label">${label}</div><div class="kpi-value" style="color:${color}">${value}</div><div class="kpi-icon" style="color:${color};background:${color}14">${icon}</div><div class="kpi-bottom"><div class="delta ${d.tone}">${d.txt}<small>vs. previous executive-complete month</small></div><div id="${sparkId}" class="spark"></div></div></div>`;}
function insight(icon,title,text,tone){return `<div class="insight"><div class="insight-icon tone-${tone}">${icon}</div><div><b>${title}</b><p>${text}</p></div></div>`;}
function highlight(value,label,color){return `<div class="highlight" style="--accent:${color}"><strong>${value}</strong><span>${label}</span></div>`;}
function heat(v,max){const t=Math.max(0,Math.min(1,max?v/max:0));const light=[239,246,255],dark=[37,99,235];const rgb=light.map((x,i)=>Math.round(x+(dark[i]-x)*t));const fg=t>.62?'#fff':'#0F172A';return `background:rgb(${rgb.join(',')});color:${fg}`;}
async function load(){try{await Promise.all(Object.entries(FILES).map(async([k,f])=>{const r=await fetch(`data/${f}`);if(!r.ok)throw new Error(`${f}: ${r.status}`);D[k]=f.endsWith('.json')?await r.json():parseCSV(await r.text());}));const complete=new Set(D.completeness.filter(x=>x.is_executive_complete==='True').map(x=>x.month));D.monthly=D.monthly.filter(x=>complete.has(x.purchase_month)).sort((a,b)=>a.purchase_month.localeCompare(b.purchase_month));D.categories=D.categories.filter(x=>complete.has(x.purchase_month)).sort((a,b)=>a.purchase_month.localeCompare(b.purchase_month));initFilters();render();document.getElementById('loading').classList.add('hidden');}catch(e){document.getElementById('loading').classList.add('hidden');const b=document.getElementById('errorBox');b.hidden=false;b.textContent=`Could not load governed project outputs: ${e.message}`;console.error(e);}}
function initFilters(){const m=document.getElementById('monthFilter'),c=document.getElementById('categoryFilter'),s=document.getElementById('stateFilter');m.innerHTML=D.monthly.map(x=>`<option value="${x.purchase_month}">${x.purchase_month}</option>`).join('');m.value=D.monthly.at(-1)?.purchase_month||'';const cats=[...new Set(D.categories.map(x=>x.category))].sort();c.innerHTML=`<option value="all">All categories</option>`+cats.map(x=>`<option value="${x}">${titleCase(x)}</option>`).join('');s.innerHTML=`<option value="all">All states</option>`+D.geography.map(x=>`<option value="${x.seller_state}">${x.seller_state}</option>`).join('');[m,c,s].forEach(el=>el.onchange=render);document.getElementById('resetFilters').onclick=()=>{m.value=D.monthly.at(-1)?.purchase_month||'';c.value='all';s.value='all';render();};}
function categorySeries(cat){return D.categories.filter(x=>x.category===cat).map(x=>({month:x.purchase_month,gmv:n(x.gmv_proxy),orders:n(x.orders),sellers:n(x.active_sellers),aov:n(x.orders)?n(x.gmv_proxy)/n(x.orders):null,late:maybe(x.late_rate),review:maybe(x.avg_review)})).sort((a,b)=>a.month.localeCompare(b.month));}
function marketplaceSeries(){return D.monthly.map(x=>({month:x.purchase_month,gmv:n(x.gmv_proxy),orders:n(x.orders),sellers:n(x.active_sellers),aov:maybe(x.aov),late:maybe(x.late_delivery_rate),review:maybe(x.avg_review_score)}));}
function contextSeries(){const cat=document.getElementById('categoryFilter').value;return cat==='all'?marketplaceSeries():categorySeries(cat);}
function contextAt(month){const series=contextSeries();return series.find(x=>x.month===month)||{month,gmv:0,orders:0,sellers:0,aov:null,late:null,review:null};}
function previousContext(month){const series=contextSeries();const i=series.findIndex(x=>x.month===month);return i>0?series[i-1]:null;}
function categoryRows(){const month=document.getElementById('monthFilter').value,sel=document.getElementById('categoryFilter').value;const all=D.categories.filter(x=>x.purchase_month===month).map(x=>({name:x.category,gmv:n(x.gmv_proxy),orders:n(x.orders),sellers:n(x.active_sellers),review:maybe(x.avg_review),late:maybe(x.late_rate)})).sort((a,b)=>b.gmv-a.gmv);if(sel==='all')return all.slice(0,5);const chosen=all.find(x=>x.name===sel);return [chosen,...all.filter(x=>x.name!==sel).slice(0,4)].filter(Boolean);}
function stateRows(){const sel=document.getElementById('stateFilter').value;const all=D.geography.map(x=>({state:x.seller_state,gmv:n(x.gmv_proxy),orders:n(x.orders),sellers:n(x.active_sellers),share:n(x.gmv_share)})).sort((a,b)=>b.gmv-a.gmv);if(sel==='all')return all.slice(0,5);const chosen=all.find(x=>x.state===sel);return [chosen,...all.filter(x=>x.state!==sel).slice(0,4)].filter(Boolean);}
function render(){charts.splice(0).forEach(c=>{try{c.dispose();}catch{}});const month=document.getElementById('monthFilter').value,cur=contextAt(month),prev=previousContext(month),series=contextSeries().filter(x=>x.month<=month),recent=series.slice(-10);const dG=delta(cur.gmv,prev?.gmv??null),dO=delta(cur.orders,prev?.orders??null),dS=delta(cur.sellers,prev?.sellers??null),dA=delta(cur.aov,prev?.aov??null),dL=delta(cur.late,prev?.late??null,true,true);document.getElementById('kpiGrid').innerHTML=kpi('GMV',moneyM(cur.gmv),COLORS.blue,'▥',dG,'spG')+kpi('Orders',compact(cur.orders),COLORS.teal,'🛒',dO,'spO')+kpi('Active Sellers',compact(cur.sellers),COLORS.blue,'♟',dS,'spS')+kpi('Avg Order Value',cur.aov===null?'N/A':money(cur.aov),COLORS.teal,'◉',dA,'spA')+kpi('Late Delivery Rate',pct(cur.late),COLORS.rose,'🚚',dL,'spL');spark('spG',recent.map(x=>x.gmv),COLORS.blue,'#DBEAFE');spark('spO',recent.map(x=>x.orders),COLORS.teal,'#CCFBF1');spark('spS',recent.map(x=>x.sellers),COLORS.blue2,'#DBEAFE');spark('spA',recent.map(x=>x.aov),COLORS.teal2,'#CCFBF1');spark('spL',recent.map(x=>x.late),COLORS.rose,'#FFE4E6');renderTrend(series);renderConcentration();renderCategories();renderStates();renderMatrix();renderNarrative(cur);}
function renderTrend(rows){ec('trendChart',{tooltip:tooltip(),legend:{top:0,left:0,itemWidth:9,itemHeight:9,textStyle:{fontSize:8,color:'#475569'},data:['GMV Proxy','Orders']},grid:{left:50,right:48,top:35,bottom:40},xAxis:{...axis(),type:'category',data:rows.map(x=>x.month),axisLabel:{color:'#64748B',fontSize:8,formatter:v=>v.replace('-','\n')}},yAxis:[{...axis(),type:'value',name:'GMV (R$M)',nameTextStyle:{fontSize:8,color:'#64748B'},axisLabel:{formatter:v=>`${(v/1e6).toFixed(1)}`,fontSize:8}},{...axis(),type:'value',name:'Orders',nameTextStyle:{fontSize:8,color:COLORS.teal},axisLabel:{formatter:v=>compact(v),color:COLORS.teal,fontSize:8}}],series:[{name:'GMV Proxy',type:'bar',data:rows.map(x=>x.gmv),itemStyle:{color:COLORS.blue,borderRadius:[2,2,0,0]}},{name:'Orders',type:'line',yAxisIndex:1,data:rows.map(x=>x.orders),smooth:.2,symbol:'none',lineStyle:{color:COLORS.teal,width:2.3},itemStyle:{color:COLORS.teal}}]});}
function renderConcentration(){const rows=[...D.concentration].sort((a,b)=>n(a.top_seller_share)-n(b.top_seller_share));ec('lorenzChart',{tooltip:{trigger:'axis',formatter:p=>`Top ${pct(p[0].value[0])} sellers<br/>${pct(p[0].value[1])} of seller GMV`},grid:{left:46,right:16,top:22,bottom:34},xAxis:{...axis(),type:'value',min:0,max:.2,name:'Top seller share',nameLocation:'middle',nameGap:24,nameTextStyle:{fontSize:8,color:'#64748B'},axisLabel:{formatter:v=>`${Math.round(v*100)}%`,fontSize:8}},yAxis:{...axis(),type:'value',min:0,max:.9,name:'GMV share',nameTextStyle:{fontSize:8,color:'#64748B'},axisLabel:{formatter:v=>`${Math.round(v*100)}%`,fontSize:8}},series:[{name:'Observed top-share points',type:'line',data:rows.map(r=>[n(r.top_seller_share),n(r.gmv_proxy_share)]),symbol:'circle',symbolSize:7,smooth:false,lineStyle:{color:COLORS.blue,width:3},itemStyle:{color:COLORS.blue},label:{show:true,formatter:p=>pct(p.value[1]),position:'top',fontSize:8,color:'#475569'}}]});document.getElementById('giniValue').textContent=n(D.headline.seller_gini).toFixed(3);document.getElementById('top20Value').textContent=pct(D.headline.top20_seller_gmv_share);}
function renderCategories(){const rows=categoryRows(),colors=['#2563EB','#3B82F6','#60A5FA','#93C5FD','#BFDBFE'];ec('categoryChart',{grid:{left:90,right:58,top:10,bottom:20},xAxis:{...axis(),type:'value',axisLabel:{formatter:v=>`R$${(v/1000).toFixed(0)}K`,fontSize:7}},yAxis:{...axis(),type:'category',inverse:true,data:rows.map(x=>titleCase(x.name)),axisLabel:{fontSize:7,width:78,overflow:'truncate'}},series:[{type:'bar',data:rows.map((x,i)=>({value:x.gmv,itemStyle:{color:colors[i]},label:{show:true,position:'right',formatter:p=>`R$ ${(p.value/1000).toFixed(1)}K`,fontSize:7}}))}]});}
function renderStates(){const rows=stateRows(),colors=['#0F766E','#0D9488','#14B8A6','#2DD4BF','#5EEAD4'];ec('stateChart',{grid:{left:40,right:58,top:10,bottom:20},xAxis:{...axis(),type:'value',axisLabel:{formatter:v=>`R$${(v/1e6).toFixed(1)}M`,fontSize:7}},yAxis:{...axis(),type:'category',inverse:true,data:rows.map(x=>x.state),axisLabel:{fontSize:8}},series:[{type:'bar',data:rows.map((x,i)=>({value:x.gmv,itemStyle:{color:colors[i]},label:{show:true,position:'right',formatter:p=>moneyM(p.value),fontSize:7}}))}]});}
function renderMatrix(){const rows=stateRows(),maxShare=Math.max(...rows.map(x=>x.share)),maxGmv=Math.max(...rows.map(x=>x.gmv)),maxSellers=Math.max(...rows.map(x=>x.sellers));document.getElementById('stateTable').innerHTML=`<thead><tr><th>State</th><th class="num">Active Sellers</th><th class="num">State GMV</th><th class="num">GMV Share</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r.state}</td><td class="num heat" style="${heat(r.sellers,maxSellers)}">${r.sellers.toLocaleString()}</td><td class="num heat" style="${heat(r.gmv,maxGmv)}">${money(r.gmv)}</td><td class="num heat" style="${heat(r.share,maxShare)}">${pct(r.share)}</td></tr>`).join('')}<tr class="total"><td>Shown rows</td><td></td><td class="num">${money(sum(rows,x=>x.gmv))}</td><td></td></tr></tbody>`;}
function renderNarrative(cur){const cat=document.getElementById('categoryFilter').value,state=document.getElementById('stateFilter').value,review=D.stats.find(x=>x.test==='late_delivery_vs_review_score'),gap=maybe(review?.effect_size),selectedState=state==='all'?null:D.geography.find(x=>x.seller_state===state),sellerBase=state==='all'?sum(D.geography,x=>x.active_sellers):n(selectedState?.active_sellers);const scope=cat==='all'?'Marketplace':titleCase(cat);document.getElementById('insights').innerHTML=insight('↗',`${scope} Momentum`,`${document.getElementById('monthFilter').value}: ${moneyM(cur.gmv)} GMV proxy and ${compact(cur.orders)} orders.`,'teal')+insight('◉','Observed Concentration',`Top 20% of sellers account for ${pct(D.headline.top20_seller_gmv_share)} of positive-GMV seller value.`,'blue')+insight('!',cur.late===null?'Category CX not available':'Operational Risk',cur.late===null?'This category mart does not contain a valid late-rate value for the selected context.':`Late-delivery rate is ${pct(cur.late)} in the selected context; late orders show a ${gap===null?'N/A':gap.toFixed(2)}-point review gap overall.`,'rose')+insight('♟',state==='all'?'Seller Base':`Seller State ${state}`,state==='all'?`${sellerBase.toLocaleString()} sellers are observed across state aggregates.`:`${sellerBase.toLocaleString()} sellers; ${pct(selectedState?.gmv_share)} of portfolio GMV proxy.`,'blue');document.getElementById('highlights').innerHTML=highlight(moneyM(D.headline.gmv_proxy),'Canonical Portfolio GMV',COLORS.blue)+highlight(n(D.headline.seller_gini).toFixed(3),'Seller Gini',COLORS.blue)+highlight(pct(D.headline.top20_seller_gmv_share),'Top 20% Seller Share',COLORS.blue)+highlight(pct(D.activation[0]?.activation_rate_le_30d),'30D Activation',COLORS.teal)+highlight(pct(D.activation[0]?.activation_rate_le_90d),'90D Activation','#0F766E')+highlight(`${gap===null?'N/A':gap.toFixed(2)} pts`,'Review Gap',COLORS.rose);}
window.addEventListener('resize',()=>charts.forEach(c=>{try{c.resize();}catch{}}));load();
