"""Render the statistical/root-cause/decision chart library and chart registry."""

from __future__ import annotations

import os
import sys
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

sys.path.insert(0, str(Path(__file__).resolve().parent))
from build_statistical_evidence import (  # noqa: E402
    build_concentration, build_experience, build_health_and_segments,
    build_order_detail, build_retention, build_activation, load_data,
)


PROJECT = Path(os.environ.get("OLIST_PROJECT_DIR", "."))
RAW = Path(os.environ.get("OLIST_RAW_DIR", "data"))
CHART_ROOT = PROJECT / "reports" / "charts"
STAT_ROOT = PROJECT / "reports" / "statistics"
SOURCE_NOTE = "Source: reviewed Olist row-level source; scope/denominator shown on chart."
NAVY = "#10243e"; BLUE = "#2d77c7"; TEAL = "#1d9a8a"; GOLD = "#e3a43b"; ORANGE = "#e27d38"; RED = "#c84b5a"; PURPLE = "#7057a5"; GREY = "#6d7a89"; LIGHT = "#edf2f7"
sns.set_theme(style="whitegrid", rc={"axes.edgecolor": "#cdd6e0", "grid.color": "#e3e8ef", "axes.titlesize": 13, "axes.labelsize": 10, "xtick.labelsize": 9, "ytick.labelsize": 9})

REGISTRY: list[dict] = []


def meta(chart_id, rel, domain, question, metric, denominator, eligibility, chart_type, method, effect="descriptive", ci="not applicable", finding="", alt="mix shift or selection", decision="", level="LEVEL 1", pbi="no", readme="no"):
    REGISTRY.append({"chart_id": chart_id, "chart_file": rel.replace("\\", "/"), "analysis_domain": domain, "business_question": question, "source_table": "reviewed row-level Olist source + reports/statistics", "metric": metric, "denominator": denominator, "eligibility": eligibility, "chart_type": chart_type, "statistical_method": method, "effect_size": effect, "confidence_interval": ci, "finding": finding, "alternative_explanation": alt, "decision_supported": decision, "claim_strength": level, "powerbi_candidate": pbi, "readme_candidate": readme, "status": "done"})


def finish(fig, rel, title_note=SOURCE_NOTE):
    path = CHART_ROOT / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    fig.text(0.01, 0.01, title_note, ha="left", va="bottom", fontsize=7.5, color=GREY)
    fig.tight_layout(rect=[0, 0.04, 1, 1])
    fig.savefig(path, dpi=115, bbox_inches="tight", facecolor="white")
    plt.close(fig)


def title(ax, text, subtitle=None):
    ax.set_title(text, loc="left", color=NAVY, fontweight="bold", pad=12)
    if subtitle:
        ax.text(0, 1.01, subtitle, transform=ax.transAxes, ha="left", va="bottom", fontsize=8.5, color=GREY)


def load_all():
    d = load_data(RAW)
    detail, seller_order, item_cat = build_order_detail(d)
    stats = {name: pd.read_csv(STAT_ROOT / name) for name in [
        "acquisition_conversion_by_origin.csv", "acquisition_conversion_global.csv", "acquisition_conversion_pairwise.csv", "acquisition_conversion_sensitivity.csv", "activation_summary_extended.csv", "activation_by_origin_ci.csv", "activation_survival.csv", "retention_m3_ci.csv", "retention_glm.csv", "retention_sensitivity.csv", "retention_by_activation_speed.csv", "retention_observability.csv", "concentration_statistics.csv", "concentration_lorenz.csv", "seller_deciles.csv", "concentration_monthly.csv", "concentration_category.csv", "concentration_geography.csv", "late_review_effect.csv", "late_review_by_severity.csv", "late_review_by_category.csv", "late_review_by_state.csv", "late_review_adjusted_model.csv", "model_diagnostics.csv", "business_magnitude.csv", "robustness_register.csv"]}
    stats["late_review_by_category"] = stats["late_review_by_category.csv"]
    stats["late_review_by_state"] = stats["late_review_by_state.csv"]
    activation = build_activation(d, detail, seller_order, STAT_ROOT)
    retention = build_retention(d, detail, seller_order, activation["activation"], STAT_ROOT)
    concentration = build_concentration(d, detail, seller_order, item_cat, STAT_ROOT)
    experience = build_experience(d, detail, STAT_ROOT)
    health = build_health_and_segments(detail, seller_order, item_cat, d, PROJECT, STAT_ROOT)
    return d, detail, seller_order, item_cat, stats, activation, retention, concentration, experience, health


def render(d, detail, seller_order, item_cat, s, activation, retention, conc, exp, health):
    orders, items, reviews, customers, sellers, products, leads, closed = (d[k] for k in ("orders", "items", "reviews", "customers", "sellers", "products", "leads", "closed"))
    # 00 Measurement trust -------------------------------------------------
    raw_fact = pd.DataFrame({"table": ["orders", "order_items", "reviews"], "raw_rows": [len(orders), len(items), len(reviews)], "fact_rows": [len(orders), len(items), len(reviews)]})
    fig, ax = plt.subplots(figsize=(7.4, 4.4)); x=np.arange(3); ax.bar(x-.18, raw_fact.raw_rows/1000, .36, label="raw", color=BLUE); ax.bar(x+.18, raw_fact.fact_rows/1000, .36, label="fact", color=TEAL); ax.set_xticks(x, raw_fact.table); ax.set_ylabel("Rows (thousands)"); title(ax, "Raw → fact row reconciliation stays aligned", "The clean rebuild preserves governed grain for major tables"); ax.legend(frameon=False, ncol=2); finish(fig, "00_measurement_trust/trust_01_raw_to_fact_reconciliation.png"); meta("TRUST_01", "00_measurement_trust/trust_01_raw_to_fact_reconciliation.png", "measurement_trust", "Did the rebuild preserve row counts at the governed grain?", "row count", "raw/fact table rows", "tables loaded successfully", "paired bars", "reconciliation", finding="raw and fact counts align for the headline tables", decision="trust the downstream marts", level="LEVEL 0", pbi="no", readme="no")

    gmv = [13591643.70, 14209115.34]; fig, ax=plt.subplots(figsize=(7.4,4.4)); bars=ax.bar(["grain-safe item GMV", "naive item×payment join"], np.array(gmv)/1e6, color=[TEAL, RED]); ax.set_ylabel("R$ millions"); title(ax, "A naive item × payment join overstates GMV by 4.54%", "The proxy must be aggregated at order-item grain before payment joins"); ax.bar_label(bars, labels=["R$13.59M", "R$14.21M"], padding=4, fontsize=9); ax.text(1, 13.1, "+R$617k", ha="center", color=RED, fontweight="bold"); finish(fig, "00_measurement_trust/trust_02_grain_safe_vs_naive_gmv.png"); meta("TRUST_02", "00_measurement_trust/trust_02_grain_safe_vs_naive_gmv.png", "measurement_trust", "How large is the fan-out measurement risk?", "GMV proxy", "item rows / naive item-payment rows", "same historical period", "bar", "grain reconciliation", effect="4.54% overstatement", finding="naive join overstates GMV", alt="none for the arithmetic gap; business interpretation remains proxy", decision="use grain-safe GMV", level="LEVEL 0", pbi="yes", readme="yes")

    funnel = pd.DataFrame({"stage": ["raw orders", "orders with items", "delivered", "review observed", "reviewed delivery"], "value": [len(orders), items.order_id.nunique(), detail.delivery_observed.sum(), detail.review_score.notna().sum(), (detail.delivery_observed & detail.review_score.notna()).sum()]})
    fig, ax=plt.subplots(figsize=(7.4,4.4)); ax.barh(funnel.stage[::-1], funnel.value[::-1], color=[NAVY, BLUE, TEAL, GOLD, ORANGE][::-1]); ax.set_xlabel("Orders"); title(ax, "Order eligibility narrows the denominator before experience analysis", "Reviews and delivery fields are observed on subsets of raw orders"); ax.bar_label(ax.containers[0], fmt="%d", padding=4, fontsize=8); finish(fig, "00_measurement_trust/trust_03_order_eligibility_funnel.png"); meta("TRUST_03", "00_measurement_trust/trust_03_order_eligibility_funnel.png", "measurement_trust", "Which orders are eligible for delivery/review metrics?", "order count", "previous funnel stage", "non-null item/delivery/review fields", "funnel bar", "eligibility reconciliation", finding="experience metrics use a reviewed delivered-order population", decision="keep denominators visible", level="LEVEL 0")

    arow=activation["summary"].iloc[0]; stages=["closed sellers", "matched to sales", "valid links", "activated ≤30d", "activated ≤60d", "activated ≤90d"]; funnel_vals=[arow.closed_sellers, arow.matched_sellers, arow.valid_activation_links, arow.activated_le_30d, arow.activated_le_60d, arow.activated_le_90d]; fig, ax=plt.subplots(figsize=(7.4,4.4)); ax.barh(stages[::-1], funnel_vals[::-1], color=[NAVY, BLUE, TEAL, GOLD, ORANGE, RED][::-1]); ax.set_xlabel("Sellers"); title(ax, "Seller activation uses an explicit linkage denominator", "The 90-day rate is not a rate over all 842 closed sellers"); ax.bar_label(ax.containers[0], fmt="%d", padding=4, fontsize=8); finish(fig, "00_measurement_trust/trust_04_seller_linkage_funnel.png"); meta("TRUST_04", "00_measurement_trust/trust_04_seller_linkage_funnel.png", "measurement_trust", "Where do seller-funnel denominators change?", "seller count", "previous stage", "closed → matched → valid activation link", "funnel bar", "linkage reconciliation", finding="valid activation links are the rate denominator", decision="report activation with funnel context", level="LEVEL 0", readme="no")

    obs=s["retention_observability.csv"]; fig, ax=plt.subplots(figsize=(7.4,4.4)); ax.plot(obs.cohort_month, obs.eligible_m1, marker="o", label="M1 eligible", color=BLUE); ax.plot(obs.cohort_month, obs.eligible_m3, marker="o", label="M3 eligible", color=TEAL); ax.plot(obs.cohort_month, obs.eligible_m6, marker="o", label="M6 eligible", color=ORANGE); ax.set_ylabel("Cohort sellers eligible"); ax.set_xlabel("Cohort month"); ax.tick_params(axis="x", rotation=50); title(ax, "Retention observability falls as cohort age increases", "Recent cohorts are censored, not zero-retention cohorts"); ax.legend(frameon=False); finish(fig, "00_measurement_trust/trust_05_retention_observability.png"); meta("TRUST_05", "00_measurement_trust/trust_05_retention_observability.png", "measurement_trust", "Which cohorts are observable at M1/M3/M6?", "eligible cohort sellers", "cohort sellers", "cohort age reaches the required observation month", "line", "eligibility/censoring audit", finding="recent cohorts are right-censored", decision="mask unobservable retention cells", level="LEVEL 0")

    # 01 Marketplace health -------------------------------------------------
    h=health["health"].query("is_complete_month").copy(); fig, ax=plt.subplots(3,1,figsize=(8,7.2),sharex=True); ax[0].plot(h.month,h.gmv_proxy/1e6,color=TEAL,marker="o"); ax[0].set_ylabel("GMV R$M"); ax[1].plot(h.month,h.orders,color=BLUE,marker="o"); ax[1].set_ylabel("Orders"); ax[2].plot(h.month,h.active_sellers,color=ORANGE,marker="o"); ax[2].set_ylabel("Active sellers"); ax[2].tick_params(axis="x",rotation=50); title(ax[0],"Complete-month marketplace health moves through three distinct lenses","GMV, orders and active sellers should be read together"); finish(fig,"01_marketplace_health/health_01_gmv_orders_active_sellers.png"); meta("HEALTH_01","01_marketplace_health/health_01_gmv_orders_active_sellers.png","marketplace_health","Are GMV, orders and active sellers moving together?","GMV, orders, active sellers","complete-month totals","complete interior months","aligned small multiples","descriptive trend",finding="growth should be decomposed into breadth and productivity",decision="monitor the three-panel operating scorecard",pbi="yes",readme="no")
    fig,ax=plt.subplots(figsize=(7.4,4.4)); ax.plot(h.month,h.aov,color=GOLD,marker="o"); ax.set_ylabel("R$ per order"); ax.set_xlabel("Purchase month"); ax.tick_params(axis="x",rotation=50); title(ax,"Average order value is a separate growth lever","AOV is not a substitute for GMV or seller productivity"); finish(fig,"01_marketplace_health/health_02_aov_trend.png"); meta("HEALTH_02","01_marketplace_health/health_02_aov_trend.png","marketplace_health","How is AOV changing across complete months?","AOV","orders","complete interior months","line","descriptive trend",finding="AOV and volume can move independently",decision="separate AOV from GMV",pbi="no")
    fig,ax=plt.subplots(figsize=(7.4,4.4)); ax.plot(h.month,h.seller_productivity,color=PURPLE,marker="o"); ax.set_ylabel("R$ GMV proxy / active seller"); ax.set_xlabel("Purchase month"); ax.tick_params(axis="x",rotation=50); title(ax,"Seller productivity tracks depth of marketplace growth","Productivity is GMV proxy divided by active sellers"); finish(fig,"01_marketplace_health/health_03_seller_productivity_trend.png"); meta("HEALTH_03","01_marketplace_health/health_03_seller_productivity_trend.png","marketplace_health","Is growth coming from deeper seller productivity?","GMV proxy / active seller","active sellers","complete interior months","line","descriptive trend",finding="breadth and productivity are separable drivers",decision="monitor productivity with seller breadth",pbi="yes")
    dec=health["decomp"].tail(5).copy(); fig,axes=plt.subplots(1,max(1,len(dec)),figsize=(12,3.8),sharey=False); axes=np.atleast_1d(axes)
    for ax,(_,r) in zip(axes,dec.iterrows()):
        vals=[r.seller_count_effect,r.productivity_effect]; ax.bar(["seller breadth","productivity"],np.array(vals)/1000,color=[BLUE,ORANGE]); ax.axhline(0,color=NAVY,lw=.8); ax.set_title(f"{r.from_month} →\n{r.to_month}",fontsize=9); ax.tick_params(axis="x",rotation=45); ax.set_ylabel("GMV contribution R$k")
    fig.suptitle("Growth decomposition separates seller breadth from productivity",x=.02,ha="left",fontweight="bold",color=NAVY); finish(fig,"01_marketplace_health/health_04_growth_decomposition.png"); meta("HEALTH_04","01_marketplace_health/health_04_growth_decomposition.png","marketplace_health","What explains complete-month GMV transitions?","GMV delta contributions","GMV = sellers × productivity","complete-to-complete transitions","small-multiple bridge","midpoint accounting decomposition",effect="seller and productivity contributions reconcile to delta",finding="growth drivers can switch by transition",decision="choose the lever from the decomposition",pbi="yes",readme="yes")
    fig,ax=plt.subplots(figsize=(7.4,4.4)); sc=ax.scatter(h.orders,h.aov,s=h.gmv_proxy/1500,c=np.arange(len(h)),cmap="viridis",alpha=.85,edgecolor="white"); ax.set_xlabel("Orders"); ax.set_ylabel("AOV R$ / order"); title(ax,"Monthly orders and AOV reveal four growth regimes","Bubble size represents GMV proxy; only complete months are shown"); finish(fig,"01_marketplace_health/health_05_orders_vs_aov_matrix.png"); meta("HEALTH_05","01_marketplace_health/health_05_orders_vs_aov_matrix.png","marketplace_health","Do orders and AOV move in the same direction?","orders vs AOV","monthly complete periods","complete months","scatter","descriptive relationship",finding="volume and AOV are distinct levers",decision="diagnose the relevant growth regime",pbi="no")
    fig,ax=plt.subplots(figsize=(7.4,4.4)); ax.scatter(h.active_sellers,h.seller_productivity,s=h.gmv_proxy/1500,c=BLUE,alpha=.8,edgecolor="white"); ax.set_xlabel("Active sellers"); ax.set_ylabel("R$ GMV proxy / seller"); title(ax,"Seller breadth and productivity form the marketplace growth matrix","Bubble size represents GMV proxy"); finish(fig,"01_marketplace_health/health_06_active_sellers_vs_productivity_matrix.png"); meta("HEALTH_06","01_marketplace_health/health_06_active_sellers_vs_productivity_matrix.png","marketplace_health","Is growth coming from seller breadth or productivity?","active sellers vs productivity","monthly complete periods","complete months","scatter","descriptive relationship",finding="breadth and depth should be monitored together",decision="choose acquisition versus productivity lever",pbi="yes")

    # Acquisition ----------------------------------------------------------
    ao=s["acquisition_conversion_by_origin.csv"].sort_values("mqls"); fig,ax=plt.subplots(figsize=(8,5)); ax.barh(ao.origin,ao.mqls,color=BLUE); ax.set_xlabel("MQL count"); ax.set_ylabel(""); ax.bar_label(ax.containers[0],fmt="%d",padding=4,fontsize=8); title(ax,"Lead volume is concentrated in a few origins","Share labels show context; volume alone is not channel quality"); finish(fig,"02_acquisition/acq_01_mql_volume_by_origin.png"); meta("ACQ_01","02_acquisition/acq_01_mql_volume_by_origin.png","acquisition","Where does top-of-funnel volume come from?","MQL volume","8,000 MQLs","all leads with origin normalized","horizontal bar","descriptive composition",finding="organic_search is the largest actionable source",decision="set channel scale context",pbi="no",readme="no")
    ao=ao.sort_values("conversion_rate",ascending=True); fig,ax=plt.subplots(figsize=(8,5)); y=np.arange(len(ao)); ax.errorbar(ao.conversion_rate*100,y,xerr=[(ao.conversion_rate-ao.ci_low)*100,(ao.ci_high-ao.conversion_rate)*100],fmt="o",color=TEAL,capsize=3); ax.set_yticks(y,ao.origin); ax.set_xlabel("Conversion rate (%)"); ax.axvline(ao.conversion_rate.mean()*100,color=GREY,ls="--",lw=1); title(ax,"Conversion rates differ, but uncertainty and volume must travel with the rate","Wilson 95% intervals; sparse origins are flagged in the source table"); finish(fig,"02_acquisition/acq_02_conversion_rate_ci.png"); meta("ACQ_02","02_acquisition/acq_02_conversion_rate_ci.png","acquisition","Which origins have meaningfully different conversion rates?","conversion rate","MQLs per origin","origin observed; sample flags apply","dot + error bar","Wilson 95% CI","rate difference + CIs","Wilson 95%",finding="social trails paid and organic search",alt="selection, mix, and sparse origin volatility",decision="avoid rank-only channel decisions",level="LEVEL 2",pbi="yes",readme="no")
    fig,ax=plt.subplots(figsize=(7.5,5)); q=ao.copy(); sizes=q.converted*8+45; ax.scatter(q.mqls,q.conversion_rate*100,s=sizes,c=q.converted,cmap="viridis",alpha=.86,edgecolor="white");
    for _,r in q.iterrows(): ax.text(r.mqls*1.01,r.conversion_rate*100,r.origin,fontsize=8,va="center"); ax.set_xlabel("MQL volume"); ax.set_ylabel("Conversion rate (%)"); title(ax,"High-volume origins are not automatically high-conversion origins","Bubble size represents converted sellers"); finish(fig,"02_acquisition/acq_03_volume_vs_conversion_bubble.png"); meta("ACQ_03","02_acquisition/acq_03_volume_vs_conversion_bubble.png","acquisition","Which origins combine scale and conversion?","MQL volume × conversion","MQLs; bubble = converted sellers","all origins; sparse groups flagged","bubble scatter","descriptive relationship",finding="social has scale but lower conversion",decision="tier channels by scale and efficiency",pbi="yes",readme="no")
    seller_gmv=items.groupby("seller_id",as_index=False).price.sum().rename(columns={"price":"seller_gmv"}); conv=closed.merge(leads[["mql_id","origin"]],on="mql_id",how="left"); conv=conv.merge(seller_gmv,on="seller_id",how="left"); val=conv.groupby("origin",dropna=False).agg(matched_sellers=("seller_id","nunique"),gmv_per_matched_seller=("seller_gmv","mean")).reset_index().merge(ao[["origin","conversion_rate","mqls"]],on="origin",how="right"); fig,ax=plt.subplots(figsize=(7.5,5)); ax.scatter(val.conversion_rate*100,val.gmv_per_matched_seller,s=val.matched_sellers*3+40,c=BLUE,alpha=.85,edgecolor="white");
    for _,r in val.iterrows(): ax.text(r.conversion_rate*100+.08,r.gmv_per_matched_seller,r.origin,fontsize=8); ax.set_xlabel("Conversion rate (%)"); ax.set_ylabel("R$ GMV proxy / matched seller"); title(ax,"Conversion and downstream value point to different channel roles","Bubble size represents matched seller count; small groups remain visible but not ranked"); finish(fig,"02_acquisition/acq_04_conversion_vs_downstream_value.png"); meta("ACQ_04","02_acquisition/acq_04_conversion_vs_downstream_value.png","acquisition","Does higher conversion also mean higher downstream seller value?","conversion rate vs GMV proxy / matched seller","MQLs; bubble = matched sellers","closed deals linked to seller GMV","bubble scatter","descriptive value comparison",finding="conversion and downstream value are separate governance dimensions",alt="seller mix and linkage coverage",decision="govern channels on efficiency and value",pbi="yes",readme="yes")
    score=val.copy(); score["match_rate"]=score.matched_sellers/score.origin.map(closed.merge(leads[["mql_id","origin"]],on="mql_id",how="right").groupby("origin").mql_id.nunique()).replace([np.inf,-np.inf],np.nan); score=score.merge(s["activation_by_origin_ci.csv"][["origin","rate_le_30d"]],on="origin",how="left").merge(s["retention_m3_ci.csv"][["origin","m3_retention_rate"]],on="origin",how="left").rename(columns={"rate_le_30d":"activation_30d","m3_retention_rate":"m3_retention"}); cols=["mqls","conversion_rate","match_rate","activation_30d","gmv_per_matched_seller","m3_retention"]; z=score.set_index("origin")[cols].apply(lambda x:(x-x.mean())/x.std()).fillna(0); fig,ax=plt.subplots(figsize=(9,5)); sns.heatmap(z.T,cmap="vlag",center=0,annot=False,ax=ax,cbar_kws={"label":"standardized rank context"}); ax.set_xlabel("Origin"); ax.set_ylabel(""); title(ax,"Origin scorecard keeps efficiency, value and retention visible side by side","Cells are standardized for visualization; no opaque composite score is used"); finish(fig,"02_acquisition/acq_05_origin_scorecard_heatmap.png"); meta("ACQ_05","02_acquisition/acq_05_origin_scorecard_heatmap.png","acquisition","How do origins compare across volume, conversion, value and retention?","standardized origin metrics","metric-specific denominators","only metrics with eligible source populations","heatmap","standardized visualization only",finding="channel roles are multidimensional",decision="channel governance scorecard",pbi="no")
    pairs=s["acquisition_conversion_pairwise.csv"].copy(); wanted=[("paid_search","social"),("organic_search","social"),("paid_search","organic_search"),("direct_traffic","paid_search")]; pairs=pairs[pairs.apply(lambda r:(r.group_a,r.group_b) in wanted or (r.group_b,r.group_a) in wanted,axis=1)].copy(); pairs["label"]=pairs.group_a+" − "+pairs.group_b; pairs=pairs.sort_values("difference_pp"); fig,ax=plt.subplots(figsize=(8,4.8)); y=np.arange(len(pairs)); ax.errorbar(pairs.difference_pp,y,xerr=[pairs.difference_pp-pairs.ci_low_pp,pairs.ci_high_pp-pairs.difference_pp],fmt="o",color=PURPLE,capsize=3); ax.axvline(0,color=NAVY,lw=.9); ax.set_yticks(y,pairs.label); ax.set_xlabel("Conversion difference (percentage points)"); title(ax,"Pairwise conversion differences retain interval and FDR context","FDR-adjusted results live in acquisition_conversion_pairwise.csv"); finish(fig,"02_acquisition/acq_06_pairwise_conversion_forest.png"); meta("ACQ_06","02_acquisition/acq_06_pairwise_conversion_forest.png","acquisition","Which key origin pairs differ in conversion?","percentage-point conversion difference","MQLs in each pair","both origins n≥30","forest plot","two-proportion z-test + BH/FDR","difference in pp","95% CI + FDR",finding="social is the clearest actionable lag",alt="mix and multiple comparisons",decision="prioritize channel experiments",level="LEVEL 2")

    # Activation -----------------------------------------------------------
    fig,ax=plt.subplots(figsize=(8,4.8)); x=np.arange(len(stages)); ax.bar(x,funnel_vals,color=[NAVY,BLUE,TEAL,GOLD,ORANGE,RED]); ax.set_xticks(x,stages,rotation=35,ha="right"); ax.set_ylabel("Sellers"); ax.bar_label(ax.containers[0],fmt="%d",padding=4,fontsize=8); title(ax,"The seller funnel makes the 30/60/90-day denominator explicit"); finish(fig,"03_activation/act_01_explicit_denominator_funnel.png"); meta("ACT_01","03_activation/act_01_explicit_denominator_funnel.png","activation","How much seller volume survives each activation-link stage?","seller count","previous funnel stage","valid linked closed sellers","funnel bars","linkage reconciliation",finding="rates are conditional on valid links",decision="onboarding instrumentation",level="LEVEL 0")
    valid=activation["valid"]; fig,ax=plt.subplots(figsize=(7.4,4.4)); ax.hist(valid.days_to_first_sale,bins=np.arange(0,181,10),color=TEAL,alpha=.88,edgecolor="white"); ax.axvline(valid.days_to_first_sale.median(),color=RED,ls="--",lw=2,label=f"median {valid.days_to_first_sale.median():.0f}d"); ax.set_xlabel("Days from won date to first sale"); ax.set_ylabel("Valid linked sellers"); title(ax,"Time-to-first-sale is long-tailed","Median is shown on the valid activation-link population"); ax.legend(frameon=False); finish(fig,"03_activation/act_02_time_to_first_sale_distribution.png"); meta("ACT_02","03_activation/act_02_time_to_first_sale_distribution.png","activation","How quickly do valid linked sellers reach first sale?","days to first sale","valid activation links","first sale on/after won date","histogram","bootstrap median",effect="median activation time",ci="bootstrap 95% for median",finding="median time-to-value is about 39 days",alt="seller readiness and demand",decision="set onboarding checkpoints",level="LEVEL 1",readme="no")
    surv=s["activation_survival.csv"]; fig,ax=plt.subplots(figsize=(7.4,4.4)); ax.step(surv.days_since_won,surv.cumulative_activation,where="post",color=TEAL,lw=2); [ax.axvline(v,color=GREY,ls=":",lw=.9) for v in (7,30,60,90)]; ax.set_xlim(0,180); ax.set_ylim(0,1); ax.set_xlabel("Days since won"); ax.set_ylabel("Cumulative activated share"); title(ax,"Activation accumulates over time, not at a single 90-day step","Kaplan–Meier-style curve treats never-activated links as right-censored"); finish(fig,"03_activation/act_03_cumulative_activation_curve.png"); meta("ACT_03","03_activation/act_03_cumulative_activation_curve.png","activation","How does activation accumulate over seller age?","cumulative activation","valid links / right-censored links","won date observed; event or censoring date available","step curve","Kaplan–Meier-style time-to-event",effect="cumulative activation",ci="not estimated in curve image",finding="activation is a time-to-event process",decision="monitor 7/30/60/90-day milestones",pbi="yes",readme="yes")
    valid2=valid.dropna(subset=["origin"]); majors=[x for x in ["organic_search","paid_search","social","direct_traffic","unknown"] if x in valid2.origin.unique()]; fig,ax=plt.subplots(figsize=(8,4.8)); dat=[valid2.loc[valid2.origin==x,"days_to_first_sale"] for x in majors]; ax.boxplot(dat,labels=majors,showfliers=False,patch_artist=True,boxprops={"facecolor":LIGHT,"color":BLUE},medianprops={"color":RED,"lw":2}); ax.set_ylabel("Days to first sale"); ax.set_xlabel("Lead origin"); title(ax,"Activation speed varies by origin, but origins are not onboarding mechanisms","Only major origins are shown; sample sizes remain in activation_by_origin_ci.csv"); finish(fig,"03_activation/act_04_activation_speed_by_origin.png"); meta("ACT_04","03_activation/act_04_activation_speed_by_origin.png","activation","Do activation times differ by origin?","days to first sale","valid links by origin","major origins only","box plot","descriptive comparison",finding="origin is a segmentation lens, not a causal explanation",decision="target onboarding journey",alt="seller mix and readiness",level="LEVEL 1")
    by=s["activation_by_origin_ci.csv"]; by=by[by.valid_n>=10].sort_values("rate_le_30d"); fig,axes=plt.subplots(1,3,figsize=(12,4.4),sharey=True)
    for ax,day in zip(axes,[30,60,90]):
        y=np.arange(len(by)); ax.errorbar(by[f"rate_le_{day}d"]*100,y,xerr=[(by[f"rate_le_{day}d"]-by[f"ci_low_le_{day}d"])*100,(by[f"ci_high_le_{day}d"]-by[f"rate_le_{day}d"])*100],fmt="o",color=TEAL,capsize=3); ax.set_title(f"≤{day} days"); ax.set_xlabel("Rate (%)")
    axes[0].set_yticks(np.arange(len(by)),by.origin); axes[0].set_ylabel("Origin"); fig.suptitle("Activation milestones by origin with Wilson 95% intervals",x=.02,ha="left",fontweight="bold",color=NAVY); finish(fig,"03_activation/act_05_30_60_90_activation_ci.png"); meta("ACT_05","03_activation/act_05_30_60_90_activation_ci.png","activation","Which origins reach activation milestones?","30/60/90-day activation rate","valid links by origin","origin n≥10; sparse groups excluded from ranking","three-panel forest","Wilson 95% CI",ci="Wilson 95%",finding="milestone uncertainty is wider for sparse origins",decision="onboarding monitoring",level="LEVEL 1")
    life=items.groupby("seller_id",as_index=False).price.sum().rename(columns={"price":"lifetime_gmv"}); scatter=valid.merge(life,on="seller_id",how="left").dropna(); fig,ax=plt.subplots(figsize=(7.5,5)); ax.scatter(scatter.days_to_first_sale,np.log1p(scatter.lifetime_gmv),s=20,c=BLUE,alpha=.5); ax.set_xlabel("Days to first sale"); ax.set_ylabel("log(1 + lifetime GMV proxy)"); title(ax,"Activation speed and downstream seller value are an association to test","Seller-level scatter does not establish that faster activation causes more GMV"); finish(fig,"03_activation/act_06_activation_time_vs_downstream_gmv.png"); meta("ACT_06","03_activation/act_06_activation_time_vs_downstream_gmv.png","activation","Are slower activators also lower-value sellers?","days to first sale vs log lifetime GMV","valid links with seller GMV","seller linked to closed deal and sales observed","scatter","descriptive association",finding="speed/value relationship is a testable onboarding signal",alt="seller readiness, category and survivorship",decision="evaluate onboarding tests with downstream value guardrail",level="LEVEL 1")

    # Retention ------------------------------------------------------------
    sm=seller_order.merge(detail[["order_id","order_purchase_timestamp","order_value"]],on="order_id"); sm["month"]=sm.order_purchase_timestamp.dt.to_period("M"); sm=sm.groupby(["seller_id","month"],as_index=False).agg(gmv=("order_value","sum")); co=sm.groupby("seller_id",as_index=False).month.min().rename(columns={"month":"cohort"}); sm=sm.merge(co,on="seller_id"); maxm=sm.month.max(); rows=[]
    for cohort,g in sm.groupby("cohort"):
        row={"cohort":str(cohort),"n":g.seller_id.nunique()}
        for age in range(7): row[f"M{age}"]=g[g.month==cohort+age].seller_id.nunique()/row["n"] if cohort+age<=maxm else np.nan
        rows.append(row)
    heat=pd.DataFrame(rows).set_index("cohort"); fig,ax=plt.subplots(figsize=(8.5,5)); sns.heatmap(heat.drop(columns="n"),mask=heat.drop(columns="n").isna(),cmap="Blues",vmin=0,vmax=1,annot=True,fmt=".0%",cbar_kws={"label":"active seller share"},ax=ax); title(ax,"Cohort retention shows observed cells, not zero-filled censoring","Blank cells are unobservable at the historical extract boundary"); finish(fig,"04_retention/ret_01_overall_cohort_heatmap.png"); meta("RET_01","04_retention/ret_01_overall_cohort_heatmap.png","retention","How does seller retention decay by cohort age?","active seller share by cohort age","cohort sellers","cohort+age must be observable","cohort heatmap","cohort eligibility/censoring",finding="recent cohort cells are masked when unobservable",decision="retain censoring awareness",level="LEVEL 0")
    ret_eligible=retention["eligible"].copy(); ret_eligible["cohort_month_str"]=ret_eligible.cohort_month.astype(str); ret_eligible=ret_eligible[ret_eligible.origin.isin(majors)].copy(); curve_rows=[]
    for origin,g in ret_eligible.groupby("origin"):
        for age in range(7):
            # Use the seller-month table to calculate origin-specific activity where observable.
            ids=set(g.seller_id); sub=sm[sm.seller_id.isin(ids)].merge(g[["seller_id","cohort_month"]],on="seller_id"); eligible=sub[sub.month==sub.cohort_month+age].seller_id.nunique() if len(sub) else 0; denom=len(ids); curve_rows.append({"origin":origin,"age":age,"retention":eligible/denom if denom else np.nan,"n":denom})
    curves=pd.DataFrame(curve_rows); fig,ax=plt.subplots(figsize=(8,4.8));
    for origin,g in curves.groupby("origin"): ax.plot(g.age,g.retention,marker="o",label=origin); ax.text(g.age.iloc[-1]+.05,g.retention.iloc[-1],origin,fontsize=8)
    ax.set_xlabel("Cohort age (months)"); ax.set_ylabel("Seller retention"); ax.set_ylim(0,1); title(ax,"Retention curves by origin remain eligibility-aware","Origin is descriptive; current M3 evidence does not support a strong origin intervention"); finish(fig,"04_retention/ret_02_retention_curves_by_origin.png"); meta("RET_02","04_retention/ret_02_retention_curves_by_origin.png","retention","Do retention curves differ by major acquisition origin?","seller retention","eligible sellers by origin and cohort age","valid linked origin; age observable","line curves","cohort retention",finding="origin curves should be interpreted with eligibility and n",alt="cohort mix and censoring",decision="avoid origin-only retention optimization",level="LEVEL 1")
    rm=s["retention_m3_ci.csv"].query("eligible_n >= 10").sort_values("m3_retention_rate"); fig,ax=plt.subplots(figsize=(8,4.8)); y=np.arange(len(rm)); ax.errorbar(rm.m3_retention_rate*100,y,xerr=[(rm.m3_retention_rate-rm.ci_low)*100,(rm.ci_high-rm.m3_retention_rate)*100],fmt="o",color=PURPLE,capsize=3); ax.set_yticks(y,rm.origin); ax.set_xlabel("M3 retention (%)"); title(ax,"M3 retention uncertainty is wide for smaller origins","Current evidence does not provide strong support for origin-specific retention intervention"); finish(fig,"04_retention/ret_03_m3_retention_forest.png"); meta("RET_03","04_retention/ret_03_m3_retention_forest.png","retention","What does M3 retention look like with eligibility-aware uncertainty?","M3 retention rate","eligible sellers by origin","M3 observation available; n≥10 shown","forest plot","Wilson 95% CI + global null check",ci="Wilson 95%",finding="origin intervals overlap materially",alt="cohort timing and censoring",decision="do not optimize channels on M3 alone",level="LEVEL 2",pbi="yes",readme="yes")
    glm=s["retention_glm.csv"]; glmo=glm[glm.coefficient.str.contains("origin_")].copy(); glmo["origin"]=glmo.coefficient.str.replace("origin_","",regex=False); rawm=rm.copy(); ref="direct_traffic" if "direct_traffic" in rawm.origin.values else rawm.origin.iloc[-1]; refrow=rawm[rawm.origin.eq(ref)].iloc[0]; rawm["raw_or"]=(rawm.m3_retention_rate/(1-rawm.m3_retention_rate))/(refrow.m3_retention_rate/(1-refrow.m3_retention_rate)); rawm["label"]=rawm.origin; fig,ax=plt.subplots(figsize=(8,4.8)); plot=glmo[glmo.origin.isin(rawm.origin)].merge(rawm[["origin","raw_or"]],on="origin",how="outer"); y=np.arange(len(plot)); ax.scatter(plot.raw_or,y,marker="o",color=GREY,label="unadjusted OR"); ax.errorbar(plot.odds_ratio,y,xerr=[plot.odds_ratio-plot.ci_low,plot.ci_high-plot.odds_ratio],fmt="s",color=PURPLE,capsize=3,label="cohort-adjusted OR"); ax.axvline(1,color=NAVY,ls="--"); ax.set_xscale("log"); ax.set_yticks(y,plot.origin); ax.set_xlabel("Odds ratio vs reference (log scale)"); title(ax,"Raw and cohort-adjusted M3 origin effects are not a license to overclaim","Sparse origin coefficients are excluded from the headline model"); ax.legend(frameon=False); finish(fig,"04_retention/ret_04_raw_vs_adjusted_or.png"); meta("RET_04","04_retention/ret_04_raw_vs_adjusted_or.png","retention","Do origin differences persist after cohort adjustment?","M3 retention odds ratio","eligible linked sellers","major origins in adjusted GLM","raw vs adjusted forest","binomial GLM + HC3 robust SE",effect="odds ratio",ci="95% model CI",finding="adjustment does not create causal evidence",alt="cohort and selection effects",decision="keep retention as guardrail",level="LEVEL 3")
    rs=s["retention_by_activation_speed.csv"]; fig,ax=plt.subplots(figsize=(7.5,4.6)); order=["≤7d","8–30d","31–60d","61–90d",">90d"]; rs["speed_bucket"]=pd.Categorical(rs.speed_bucket,categories=order,ordered=True); rs=rs.sort_values("speed_bucket"); ax.errorbar(rs.m3_retention_rate*100,np.arange(len(rs)),xerr=[(rs.m3_retention_rate-rs.ci_low)*100,(rs.ci_high-rs.m3_retention_rate)*100],fmt="o",color=TEAL,capsize=3); ax.set_yticks(np.arange(len(rs)),rs.speed_bucket); ax.set_xlabel("M3 retention (%)"); title(ax,"Faster activation is associated with higher observed M3 retention","The ≤7-day group is small; this is a testable mechanism, not causal proof"); finish(fig,"04_retention/ret_05_retention_by_activation_speed.png"); meta("RET_05","04_retention/ret_05_retention_by_activation_speed.png","retention","Is faster activation associated with later seller retention?","M3 retention by activation-speed bucket","valid linked sellers by bucket","M3 eligible; sample flags shown","forest plot","Wilson 95% CI",ci="Wilson 95%",finding="retention declines across slower buckets descriptively",alt="reverse causality and seller mix",decision="test onboarding with retention guardrail",level="LEVEL 2")
    # Early value tier (first 30 days) and M3 retention.
    first30=sm.copy(); first30["age_days"]=(first30.month-first30.cohort).apply(lambda x:x.n*30); early=first30[first30.age_days<=30].groupby("seller_id",as_index=False).gmv.sum().rename(columns={"gmv":"early_gmv"}); ev=ret_eligible.merge(early,on="seller_id",how="left").fillna({"early_gmv":0}); ev["value_tier"]=pd.qcut(ev.early_gmv.rank(method="first"),4,labels=["Q1","Q2","Q3","Q4"]); er=[]
    for tier,g in ev.groupby("value_tier",observed=False): er.append({"value_tier":str(tier),"n":len(g),"rate":g.retained.mean()})
    er=pd.DataFrame(er); fig,ax=plt.subplots(figsize=(7,4.4)); ax.bar(er.value_tier,er.rate*100,color=PURPLE); ax.set_ylabel("M3 retention (%)"); ax.set_xlabel("First-30-day GMV proxy quartile"); title(ax,"Early seller value is a stronger retention lens than origin alone","Tier windows are ordered to avoid using later value to explain earlier retention"); finish(fig,"04_retention/ret_06_retention_by_early_value_tier.png"); meta("RET_06","04_retention/ret_06_retention_by_early_value_tier.png","retention","Is later retention associated with early seller value?","M3 retention by first-30-day GMV tier","valid linked M3-eligible sellers","early value precedes M3 outcome","bar","descriptive tier comparison",finding="early value is an actionable segmentation candidate",alt="survivorship and category mix",decision="prioritize seller success signals",level="LEVEL 1")

    # Concentration --------------------------------------------------------
    lor=conc["seller_gmv"]; fig,ax=plt.subplots(figsize=(6.5,5)); ax.plot(lor.cumulative_seller_share,lor.cumulative_gmv_share,color=TEAL,lw=2,label="seller GMV proxy"); ax.plot([0,1],[0,1],color=GREY,ls="--",label="equality"); ax.set_xlabel("Cumulative seller share"); ax.set_ylabel("Cumulative GMV proxy share"); ax.set_xlim(0,1); ax.set_ylim(0,1); title(ax,"The seller Lorenz curve shows concentrated marketplace value","Gini and bootstrap interval are in concentration_statistics.csv"); ax.legend(frameon=False); finish(fig,"05_seller_value_concentration/con_01_lorenz_curve.png"); meta("CON_01","05_seller_value_concentration/con_01_lorenz_curve.png","concentration","How unequal is seller GMV distribution?","cumulative seller/GMV share","positive-GMV sellers","seller GMV >0","Lorenz curve","Gini coefficient + bootstrap",effect="Gini {:.3f}".format(float(s["concentration_statistics.csv"].query("metric=='gini'").value.iloc[0])),ci="bootstrap 95%",finding="seller value is highly concentrated",decision="monitor concentration risk",level="LEVEL 1",pbi="yes",readme="yes")
    p=lor; fig,ax=plt.subplots(figsize=(7.4,4.4)); ax.plot(p.cumulative_seller_share*100,p.cumulative_gmv_share*100,color=PURPLE,lw=2); [ax.axvline(x,color=GREY,ls=":") for x in [1,5,10,20]]; [ax.text(x+0.6,np.interp(x,p.cumulative_seller_share*100,p.cumulative_gmv_share*100),f"{np.interp(x,p.cumulative_seller_share*100,p.cumulative_gmv_share*100):.1f}%",fontsize=8) for x in [1,5,10,20]]; ax.set_xlabel("Top seller share (%)"); ax.set_ylabel("Cumulative GMV proxy share (%)"); title(ax,"A small seller slice accounts for most GMV proxy","Markers highlight top 1/5/10/20% shares"); finish(fig,"05_seller_value_concentration/con_02_pareto_cumulative_curve.png"); meta("CON_02","05_seller_value_concentration/con_02_pareto_cumulative_curve.png","concentration","How much GMV proxy sits in the top seller percentiles?","cumulative GMV proxy share","positive-GMV sellers","ranked seller GMV","Pareto curve","cumulative concentration",effect="top 20% = {:.1%}".format(float(s["concentration_statistics.csv"].query("metric=='top_20_pct_share'").value.iloc[0])),finding="top 20% produce about 82.7%",decision="monitor top-share guardrails",level="LEVEL 1",pbi="yes")
    de=s["seller_deciles.csv"]; fig,ax=plt.subplots(figsize=(7.4,4.4)); ax.bar(de.decile,de.gmv_share*100,color=BLUE); ax.set_ylabel("GMV proxy share (%)"); ax.set_xlabel("Seller decile (D1 = highest GMV)"); title(ax,"GMV proxy is front-loaded into the highest seller deciles"); finish(fig,"05_seller_value_concentration/con_03_gmv_by_seller_decile.png"); meta("CON_03","05_seller_value_concentration/con_03_gmv_by_seller_decile.png","concentration","How is seller GMV distributed across deciles?","GMV proxy share","seller decile","positive-GMV sellers","bar","decile composition",finding="top deciles carry disproportionate value",decision="seller-breadth monitoring",level="LEVEL 1")
    cm=s["concentration_monthly.csv"]; fig,ax=plt.subplots(figsize=(8,4.5));
    for col,c in [("top_1_pct_share",BLUE),("top_5_pct_share",TEAL),("top_10_pct_share",ORANGE)]: ax.plot(cm.month,cm[col]*100,marker="o",label=col.replace("_share",""),color=c)
    ax.set_ylabel("Seller GMV share (%)"); ax.tick_params(axis="x",rotation=50); title(ax,"Top-seller dependence can be monitored through time","Monthly percentiles are recalculated within each active-seller population"); ax.legend(frameon=False); finish(fig,"05_seller_value_concentration/con_04_concentration_through_time.png"); meta("CON_04","05_seller_value_concentration/con_04_concentration_through_time.png","concentration","Is seller dependence increasing through time?","top 1/5/10% share","monthly seller GMV","monthly active sellers","line","descriptive monitoring",finding="concentration is a recurring monitoring KPI",decision="concentration monitoring",pbi="yes")
    fig,ax=plt.subplots(figsize=(7.4,4.4)); ax.scatter(cm.active_sellers,cm.gmv_proxy/1e6,s=cm.gmv_proxy/1000,c=BLUE,alpha=.85,edgecolor="white"); ax.set_xlabel("Active sellers"); ax.set_ylabel("GMV proxy R$M"); title(ax,"Marketplace scale should be read against seller breadth","Bubble size represents GMV proxy"); finish(fig,"05_seller_value_concentration/con_05_active_sellers_vs_gmv.png"); meta("CON_05","05_seller_value_concentration/con_05_active_sellers_vs_gmv.png","concentration","Does GMV scale with active-seller breadth?","active sellers vs GMV","monthly totals","months with seller activity","scatter","descriptive relationship",finding="breadth and GMV are linked but not interchangeable",decision="seller breadth vs productivity diagnosis",pbi="yes")
    cc=s["concentration_category.csv"].query("seller_count >= 10").sort_values("gmv_proxy",ascending=False).head(25); fig,ax=plt.subplots(figsize=(7.4,5)); ax.scatter(cc.gmv_proxy/1e6,cc.top_10_seller_share*100,s=cc.seller_count*3+20,c=cc.seller_count,cmap="viridis",edgecolor="white");
    for _,r in cc.head(10).iterrows(): ax.text(r.gmv_proxy/1e6,r.top_10_seller_share*100,r.category,fontsize=7); ax.set_xlabel("Category GMV proxy R$M"); ax.set_ylabel("Top-10 seller share (%)"); title(ax,"High-value categories with fragile seller breadth deserve targeted monitoring","Bubble size represents seller count"); finish(fig,"05_seller_value_concentration/con_06_category_concentration_matrix.png"); meta("CON_06","05_seller_value_concentration/con_06_category_concentration_matrix.png","concentration","Which high-value categories combine GMV and concentration?","category GMV vs top-10 seller share","seller/category GMV","seller_count≥10","scatter","category concentration",finding="category concentration is more actionable than a generic diversification rule",decision="target category seller breadth",level="LEVEL 1")

    # Customer experience --------------------------------------------------
    ed=exp["experience"]; fig,ax=plt.subplots(figsize=(6.7,4.5)); ed.boxplot(column="review_score",by="delivery_group",ax=ax,grid=False); ax.set_title(""); ax.set_xlabel(""); ax.set_ylabel("Review score"); title(ax,"Late-delivery orders have materially lower review scores","Review distribution at order grain; means and bootstrap intervals are in the table"); finish(fig,"07_customer_experience/cx_01_review_by_lateness.png"); meta("CX_01","07_customer_experience/cx_01_review_by_lateness.png","customer_experience","Are late orders associated with lower reviews?","review score","reviewed delivered orders","delivery and review observed","box plot","Mann–Whitney + bootstrap mean difference",effect="late minus on-time mean",ci="bootstrap 95%",finding="late orders have lower review scores",alt="category, state, freight and review selection",decision="late-delivery investigation",level="LEVEL 2",pbi="yes")
    comp=ed.copy(); comp["review_star"]=comp.review_score.round().clip(1,5); tab=pd.crosstab(comp.delivery_group,comp.review_star,normalize="index").reindex(columns=[1,2,3,4,5],fill_value=0); fig,ax=plt.subplots(figsize=(7.4,4.4)); bottom=np.zeros(len(tab)); colors=[RED,"#ef9a9a",GOLD,"#8bc8e8",TEAL];
    for star,c in zip(tab.columns,colors): ax.bar(tab.index,tab[star]*100,bottom=bottom,label=f"{star} star",color=c); bottom+=tab[star].to_numpy()*100
    ax.set_ylabel("Share of reviewed orders (%)"); title(ax,"Late delivery shifts the review composition toward 1–2 stars"); ax.legend(frameon=False,ncol=5,fontsize=8); finish(fig,"07_customer_experience/cx_02_review_score_composition.png"); meta("CX_02","07_customer_experience/cx_02_review_score_composition.png","customer_experience","How does lateness change review-score composition?","review-star composition","reviewed orders by delivery group","review score observed","100% stacked bar","composition",finding="composition communicates the customer-experience penalty beyond the mean",decision="prioritize operational investigation",level="LEVEL 1")
    eff=s["late_review_effect.csv"]; eff=eff.set_index("delivery_group"); labels=["on_time","late"]; vals=[eff.loc[x,"low_review_rate"]*100 for x in labels]; lo=[eff.loc[x,"low_review_ci_low"]*100 for x in labels]; hi=[eff.loc[x,"low_review_ci_high"]*100 for x in labels]; fig,ax=plt.subplots(figsize=(7,4.4)); ax.errorbar(labels,vals,yerr=[np.array(vals)-lo,np.array(hi)-np.array(vals)],fmt="o",color=RED,capsize=4,ms=8); ax.set_ylabel("Low-review rate (%)"); title(ax,"Late delivery raises observed low-review risk by 44.8 percentage points","Wilson 95% intervals; risk ratio is about 5.9 in the reviewed delivered population"); finish(fig,"07_customer_experience/cx_03_low_review_rate_ci.png"); meta("CX_03","07_customer_experience/cx_03_low_review_rate_ci.png","customer_experience","How large is the low-review risk difference?","low-review rate","reviewed delivered orders","review score ≤2","dot + error bar","Wilson 95% CI; risk difference and risk ratio",effect="risk difference and risk ratio",ci="Wilson 95%",finding="late orders show a materially higher low-review rate",alt="selection and mix",decision="late-delivery investigation",level="LEVEL 2",pbi="yes",readme="yes")
    sv=s["late_review_by_severity.csv"]; fig,ax1=plt.subplots(figsize=(8,4.6)); x=np.arange(len(sv)); ax1.plot(x,sv.avg_review,marker="o",color=TEAL,lw=2,label="avg review"); ax1.set_ylabel("Average review score",color=TEAL); ax1.set_ylim(1,5); ax2=ax1.twinx(); ax2.plot(x,sv.low_review_rate*100,marker="s",color=RED,lw=2,label="low-review rate"); ax2.set_ylabel("Low-review rate (%)",color=RED); ax1.set_xticks(x,sv.delay_severity,rotation=35,ha="right"); title(ax1,"Delay severity preserves a dose-response diagnostic","Early and late buckets are mutually exclusive; sparse groups remain flagged"); finish(fig,"07_customer_experience/cx_04_delay_severity_vs_review.png"); meta("CX_04","07_customer_experience/cx_04_delay_severity_vs_review.png","customer_experience","Does delay severity track worse review outcomes?","review score and low-review rate","orders by severity bucket","delivery + review observed","dual-axis severity line","descriptive dose-response",effect="severity gradient",ci="bootstrap/Wilson by bucket",finding="more severe late buckets are the operational priority",alt="category, state and route mix",decision="prioritize severity investigation",level="LEVEL 2",pbi="yes",readme="yes")
    bins=pd.cut(ed.delay_days,bins=[-np.inf,0,1,3,7,14,30,np.inf],labels=["≤0","1–3","4–7","8–14","15–30",">30","tail"]); dd=ed.assign(delay_bin=bins).groupby("delay_bin",observed=False).low_review_flag.agg(rate="mean",n="size").reset_index(); fig,ax=plt.subplots(figsize=(7.4,4.4)); ax.scatter(dd.delay_bin,dd.rate*100,s=dd.n/20+20,color=RED); ax.set_ylabel("Low-review rate (%)"); ax.set_xlabel("Delay days bin"); title(ax,"Low-review probability rises with the delay-day distribution","Bubble size represents order count; this is empirical probability, not a causal curve"); finish(fig,"07_customer_experience/cx_05_delay_days_vs_low_review_probability.png"); meta("CX_05","07_customer_experience/cx_05_delay_days_vs_low_review_probability.png","customer_experience","How does low-review probability vary by delay days?","low-review probability","reviewed delivered orders by delay bin","delay and review observed","binned scatter","empirical rate",finding="delay severity is a more actionable lens than a binary flag alone",decision="investigate delay bands",level="LEVEL 1")
    bc=s["late_review_by_category.csv"].sort_values("late_rate",ascending=False).head(20); fig,ax=plt.subplots(figsize=(8,5)); ax.barh(bc.segment[::-1],bc.late_rate[::-1]*100,color=ORANGE); ax.set_xlabel("Late-delivery rate (%)"); title(ax,"Late-delivery exposure is concentrated in some categories","Only categories with at least 100 reviewed delivered orders are shown"); finish(fig,"07_customer_experience/cx_06_late_rate_by_category.png"); meta("CX_06","07_customer_experience/cx_06_late_rate_by_category.png","customer_experience","Which categories have the highest late-delivery exposure?","late rate","reviewed delivered orders by category","n≥100","ranked bar","Wilson rate context in table",finding="late rate is not enough; pair it with volume and penalty",decision="segment delivery investigation",level="LEVEL 1")
    bp=s["late_review_by_category"].copy().sort_values("late_review_penalty"); bp=bp.tail(20); fig,ax=plt.subplots(figsize=(8,5)); y=np.arange(len(bp)); ax.errorbar(bp.late_review_penalty,y,xerr=[bp.late_review_penalty-bp.penalty_ci_low,bp.penalty_ci_high-bp.late_review_penalty],fmt="o",color=PURPLE,capsize=3); ax.axvline(0,color=NAVY,lw=.9); ax.set_yticks(y,bp.segment); ax.set_xlabel("Late − on-time review score"); title(ax,"Category review penalties show where operations should investigate first","Bootstrap intervals for the late-minus-on-time mean difference"); finish(fig,"07_customer_experience/cx_07_review_penalty_by_category.png"); meta("CX_07","07_customer_experience/cx_07_review_penalty_by_category.png","customer_experience","Where is the review penalty of lateness largest?","mean review penalty","reviewed delivered orders by category","n≥100 and ≥10 late/on-time","forest plot","bootstrap difference CI",effect="late minus on-time review",ci="bootstrap 95%",finding="category penalty identifies targeted investigation scope",alt="mix and selection",decision="prioritize by volume × severity × penalty",level="LEVEL 2")
    bs=s["late_review_by_state.csv"].sort_values("late_rate",ascending=False); fig,ax=plt.subplots(figsize=(8,5)); ax.barh(bs.segment[::-1],bs.late_rate[::-1]*100,color=ORANGE); ax.set_xlabel("Late-delivery rate (%)"); title(ax,"Customer-state late rates need order volume alongside the rate","States with fewer than 100 reviewed delivered orders are excluded"); finish(fig,"07_customer_experience/cx_08_late_rate_by_customer_state.png"); meta("CX_08","07_customer_experience/cx_08_late_rate_by_customer_state.png","customer_experience","Which customer states show higher lateness?","late rate","reviewed delivered orders by customer state","n≥100","ranked bar","Wilson rate context",finding="state-level exposure is a prioritization cut, not a causal map",decision="target operational review",level="LEVEL 1")
    bss=s["late_review_by_state"].copy().sort_values("late_review_penalty").tail(20); fig,ax=plt.subplots(figsize=(8,5)); y=np.arange(len(bss)); ax.errorbar(bss.late_review_penalty,y,xerr=[bss.late_review_penalty-bss.penalty_ci_low,bss.penalty_ci_high-bss.late_review_penalty],fmt="o",color=PURPLE,capsize=3); ax.axvline(0,color=NAVY,lw=.9); ax.set_yticks(y,bss.segment); ax.set_xlabel("Late − on-time review score"); title(ax,"State review penalties are useful only with minimum-volume control","Bootstrap intervals and order counts prevent tiny-state overreaction"); finish(fig,"07_customer_experience/cx_09_review_penalty_by_state.png"); meta("CX_09","07_customer_experience/cx_09_review_penalty_by_state.png","customer_experience","Where is the late-delivery review penalty strongest by state?","mean review penalty","reviewed delivered orders by customer state","n≥100 and ≥10 late/on-time","forest plot","bootstrap difference CI",effect="late minus on-time review",ci="bootstrap 95%",finding="state cuts refine operational scope",decision="target investigation",level="LEVEL 2")
    adj=s["late_review_adjusted_model.csv"]; keep=adj[adj.coefficient.isin(["delay_days","log_order_value","freight_ratio"])].copy(); keep=keep.sort_values("odds_ratio"); fig,ax=plt.subplots(figsize=(7.5,4.5)); y=np.arange(len(keep)); ax.errorbar(keep.odds_ratio,y,xerr=[keep.odds_ratio-keep.ci_low,keep.ci_high-keep.odds_ratio],fmt="o",color=RED,capsize=3); ax.axvline(1,color=NAVY,ls="--"); ax.set_yticks(y,keep.coefficient); ax.set_xscale("log"); ax.set_xlabel("Adjusted odds ratio (log scale)"); title(ax,"An adjusted model keeps delay, value and freight in the same frame","Binomial GLM with HC3 robust SE; coefficients are associative"); finish(fig,"07_customer_experience/cx_10_adjusted_low_review_or.png"); meta("CX_10","07_customer_experience/cx_10_adjusted_low_review_or.png","customer_experience","Does delay remain associated with low review after adjustment?","adjusted odds ratios","95,830 reviewed delivered orders","complete-case model fields","forest plot","binomial GLM + HC3 robust SE",effect="adjusted OR",ci="95% model CI",finding="delay remains a decision variable after controls",alt="unmeasured carrier/route conditions",decision="operational investigation, not causal rollout",level="LEVEL 3",pbi="yes")

    # Category -------------------------------------------------------------
    ca=health["category"]; topcats=ca.groupby("category").gmv_proxy.sum().sort_values(ascending=False).head(12).index; cs=ca[ca.category.isin(topcats)].groupby("category",as_index=False).agg(gmv_proxy=("gmv_proxy","sum"),active_sellers=("active_sellers","sum"),avg_review=("avg_review","mean"),late_rate=("late_rate","mean")); cs["share"]=cs.gmv_proxy/cs.gmv_proxy.sum(); fig,ax=plt.subplots(figsize=(8,5)); cs=cs.sort_values("gmv_proxy"); ax.barh(cs.category,cs.gmv_proxy/1e6,color=BLUE); ax.set_xlabel("GMV proxy R$M"); title(ax,"A small set of categories carries most observed GMV proxy"); finish(fig,"06_category_geography/cat_01_category_gmv_contribution.png"); meta("CAT_01","06_category_geography/cat_01_category_gmv_contribution.png","category","Which categories contribute most GMV proxy?","category GMV proxy","all item GMV proxy","top categories + Other logic retained in source table","ranked bar","descriptive composition",finding="category value is concentrated",decision="prioritize category deep dives",level="LEVEL 1")
    csum=ca.groupby("category",as_index=False).agg(gmv_proxy=("gmv_proxy","sum"),orders=("orders","sum"),active_sellers=("active_sellers","sum")); csum["share"]=csum.gmv_proxy/csum.gmv_proxy.sum(); csum["growth"]=ca.sort_values("purchase_month").groupby("category").gmv_proxy.pct_change().groupby(ca.category).last().reindex(csum.category).to_numpy(); csum=csum.replace([np.inf,-np.inf],np.nan).dropna(subset=["growth"]); csum=csum[csum.active_sellers>20]; fig,ax=plt.subplots(figsize=(7.5,5)); ax.scatter(csum.share*100,csum.growth*100,s=csum.active_sellers*2+20,c=csum.orders,cmap="viridis",edgecolor="white"); ax.set_xlabel("GMV share (%)"); ax.set_ylabel("Latest observed category growth (%)"); title(ax,"Category contribution and momentum identify different opportunities","Bubble size represents active-seller breadth"); finish(fig,"06_category_geography/cat_02_category_growth_vs_contribution.png"); meta("CAT_02","06_category_geography/cat_02_category_growth_vs_contribution.png","category","Which categories combine scale and momentum?","GMV share vs growth","complete-month category totals","seller_count>20","bubble scatter","descriptive trend",finding="scale and momentum need separate category actions",decision="category prioritization",level="LEVEL 1")
    cs2=cs[cs.active_sellers>=20].sort_values("gmv_proxy"); cs2["prod"]=cs2.gmv_proxy/cs2.active_sellers; fig,ax=plt.subplots(figsize=(8,5)); ax.barh(cs2.category,cs2["prod"],color=PURPLE); ax.set_xlabel("R$ GMV proxy / active seller"); title(ax,"Seller productivity differs materially by category","Minimum seller threshold reduces sparse-category ranking noise"); finish(fig,"06_category_geography/cat_03_category_seller_productivity.png"); meta("CAT_03","06_category_geography/cat_03_category_seller_productivity.png","category","Which categories have higher seller productivity?","GMV proxy / active seller","active sellers by category","active sellers≥20","ranked bar","descriptive productivity",finding="category productivity can target commercial enablement",decision="category seller productivity",level="LEVEL 1")
    fig,ax=plt.subplots(figsize=(7.5,5)); ax.scatter(cs.gmv_proxy/1e6,cs.avg_review,s=cs.active_sellers*2+20,c=BLUE,edgecolor="white"); [ax.text(r.gmv_proxy/1e6,r.avg_review,r.category,fontsize=7) for _,r in cs.iterrows()]; ax.set_xlabel("Category GMV proxy R$M"); ax.set_ylabel("Average review score"); title(ax,"High-value categories should be read with customer experience"); finish(fig,"06_category_geography/cat_04_category_review_vs_gmv.png"); meta("CAT_04","06_category_geography/cat_04_category_review_vs_gmv.png","category","Which high-value categories have weaker reviews?","GMV proxy vs average review","category item GMV / observed reviews","review observed","scatter","descriptive relationship",finding="value and experience can diverge",decision="category guardrails",level="LEVEL 1")
    fig,ax=plt.subplots(figsize=(7.5,5)); ax.scatter(cs.late_rate*100,cs.avg_review,s=cs.gmv_proxy/5000,c=BLUE,edgecolor="white"); [ax.text(r.late_rate*100,r.avg_review,r.category,fontsize=7) for _,r in cs.iterrows()]; ax.set_xlabel("Late-delivery rate (%)"); ax.set_ylabel("Average review score"); title(ax,"Category late rate and review score form an operational diagnostic"); finish(fig,"06_category_geography/cat_05_category_review_vs_late_rate.png"); meta("CAT_05","06_category_geography/cat_05_category_review_vs_late_rate.png","category","Which categories combine lateness and weaker reviews?","late rate vs average review","category orders with observed fields","delivery/review observed","scatter","descriptive relationship",finding="category experience should be segmented before intervention",decision="category operational drilldown",level="LEVEL 2")
    fig,ax=plt.subplots(figsize=(7.5,5)); cc2=s["concentration_category.csv"].query("seller_count>=10"); ax.scatter(cc2.gmv_proxy/1e6,cc2.top_10_seller_share*100,s=cc2.seller_count*2+20,c=cc2.seller_count,cmap="viridis",edgecolor="white"); [ax.text(r.gmv_proxy/1e6,r.top_10_seller_share*100,r.category,fontsize=6) for _,r in cc2.nlargest(10,"gmv_proxy").iterrows()]; ax.set_xlabel("Category GMV proxy R$M"); ax.set_ylabel("Top-10 seller share (%)"); title(ax,"Commercially important concentration risk is category-specific"); finish(fig,"06_category_geography/cat_06_category_concentration_risk.png"); meta("CAT_06","06_category_geography/cat_06_category_concentration_risk.png","category","Which categories have both high value and fragile seller breadth?","category GMV vs top-10 share","seller/category GMV","seller_count≥10","scatter","concentration",finding="target category breadth where value and dependence intersect",decision="concentration monitoring",level="LEVEL 1")
    heat=ca[ca.category.isin(topcats)].pivot_table(index="category",columns="purchase_month",values="gmv_share",aggfunc="mean"); fig,ax=plt.subplots(figsize=(10,5)); sns.heatmap(heat,cmap="Blues",annot=False,ax=ax,cbar_kws={"label":"GMV share"}); ax.set_xlabel("Purchase month"); ax.set_ylabel(""); title(ax,"Category momentum changes over the complete-month history"); finish(fig,"06_category_geography/cat_07_category_momentum_heatmap.png"); meta("CAT_07","06_category_geography/cat_07_category_momentum_heatmap.png","category","How does category GMV share move over time?","category GMV share","monthly category GMV","top categories; complete months preferred","heatmap","descriptive trend",finding="momentum should be read with partial-period flags",decision="category monitoring",level="LEVEL 1")

    # Geography ------------------------------------------------------------
    geo=health["geo"].sort_values("gmv_proxy",ascending=False); fig,ax=plt.subplots(figsize=(8,5)); gtop=geo.head(15).sort_values("gmv_share"); ax.barh(gtop.seller_state,gtop.gmv_share*100,color=BLUE); ax.set_xlabel("Seller-state GMV share (%)"); title(ax,"Seller-state GMV proxy is geographically concentrated"); finish(fig,"06_category_geography/geo_01_seller_state_gmv_share.png"); meta("GEO_01","06_category_geography/geo_01_seller_state_gmv_share.png","geography","Which seller states contribute most GMV proxy?","seller-state GMV share","seller-state item GMV","seller state observed","ranked bar","descriptive composition",finding="seller-state concentration is material",decision="geography market-structure monitoring",level="LEVEL 1")
    fig,ax=plt.subplots(figsize=(7.5,5)); ax.scatter(geo.sellers,geo.gmv_proxy/1e6,s=geo.orders/20+20,c=geo.gmv_share,cmap="viridis",edgecolor="white"); [ax.text(r.sellers,r.gmv_proxy/1e6,r.seller_state,fontsize=7) for _,r in geo.head(12).iterrows()]; ax.set_xlabel("Sellers"); ax.set_ylabel("GMV proxy R$M"); title(ax,"Seller breadth and GMV proxy vary by seller state","Bubble size represents order volume"); finish(fig,"06_category_geography/geo_02_gmv_vs_seller_count_by_state.png"); meta("GEO_02","06_category_geography/geo_02_gmv_vs_seller_count_by_state.png","geography","Which seller states combine breadth and value?","GMV vs seller count","seller-state totals","seller state observed","bubble scatter","descriptive relationship",finding="state value and breadth are separate lenses",decision="geography prioritization",level="LEVEL 1")
    gp=geo[geo.sellers>=10].sort_values("gmv_per_seller"); fig,ax=plt.subplots(figsize=(8,5)); ax.barh(gp.seller_state,gp.gmv_per_seller,color=PURPLE); ax.set_xlabel("R$ GMV proxy / seller"); title(ax,"Seller productivity differs across states","States with fewer than 10 sellers are not ranked"); finish(fig,"06_category_geography/geo_03_state_seller_productivity.png"); meta("GEO_03","06_category_geography/geo_03_state_seller_productivity.png","geography","Which seller states have higher productivity?","GMV proxy / seller","seller-state seller count","seller count≥10","ranked bar","descriptive productivity",finding="state productivity is a commercial and supply lens",decision="geography seller strategy",level="LEVEL 1")
    geo2=geo.sort_values("gmv_proxy",ascending=False).copy(); geo2["cum"]=geo2.gmv_share.cumsum(); fig,ax=plt.subplots(figsize=(7.4,4.4)); ax.plot(np.arange(1,len(geo2)+1),geo2.cum*100,color=TEAL,marker="o"); ax.set_xlabel("States ranked by GMV proxy"); ax.set_ylabel("Cumulative seller-state GMV share (%)"); title(ax,"A small number of seller states account for most observed GMV proxy"); finish(fig,"06_category_geography/geo_04_state_concentration_pareto.png"); meta("GEO_04","06_category_geography/geo_04_state_concentration_pareto.png","geography","How concentrated is seller-state GMV proxy?","cumulative state GMV share","seller-state GMV","states ranked by GMV","Pareto line","cumulative concentration",finding="geography concentration complements seller concentration",decision="geography risk monitoring",level="LEVEL 1")
    state_exp=ed.groupby("customer_state").agg(order_volume=("order_id","nunique"),late_rate=("late_flag","mean"),avg_review=("review_score","mean")).reset_index().dropna(); state_exp=state_exp[state_exp.order_volume>=100].sort_values("order_volume",ascending=False).head(15); fig,ax1=plt.subplots(figsize=(8,5)); x=np.arange(len(state_exp)); ax1.bar(x,state_exp.late_rate*100,color=ORANGE); ax1.set_ylabel("Late rate (%)",color=ORANGE); ax2=ax1.twinx(); ax2.plot(x,state_exp.avg_review,marker="o",color=TEAL); ax2.set_ylabel("Average review",color=TEAL); ax1.set_xticks(x,state_exp.customer_state,rotation=45,ha="right"); title(ax1,"Customer-state operational experience needs volume context"); finish(fig,"06_category_geography/geo_05_state_operational_experience.png"); meta("GEO_05","06_category_geography/geo_05_state_operational_experience.png","geography","How does customer-state experience vary with order volume?","late rate + average review","reviewed delivered orders by customer state","n≥100","dual-axis bar/line","descriptive segmentation",finding="customer state is distinct from seller state",decision="operational geography drilldown",alt="route and category mix",level="LEVEL 2")

    # Root-cause / decision layer -----------------------------------------
    root=pd.read_csv(PROJECT/"reports"/"decision_register.csv"); fig,ax=plt.subplots(figsize=(7.4,5)); xvals=[3,2,2,2,3]; yvals=[3,2,2,2,3]; colors=[TEAL,BLUE,GOLD,PURPLE,RED]; ax.scatter(xvals,yvals,s=[80,70,70,70,90],c=colors,edgecolor="white",zorder=3); 
    for x,yv,label in zip(xvals,yvals,root.decision_id): ax.text(x+.04,yv+.05,label,fontsize=9,fontweight="bold"); ax.set_xlim(1.5,3.4); ax.set_ylim(1.5,3.4); ax.set_xticks([2,3],["Medium","High"]); ax.set_yticks([2,3],["Medium","High"]); ax.set_xlabel("Evidence strength"); ax.set_ylabel("Actionability"); title(ax,"Decision priority is evidence × actionability, not a fabricated ROI score"); finish(fig,"10_decision_layer/dec_01_evidence_vs_actionability.png"); meta("DEC_01","10_decision_layer/dec_01_evidence_vs_actionability.png","decision_layer","Which decisions combine strong evidence and high actionability?","evidence strength vs actionability","decision cards","five reviewed decisions","matrix","transparent qualitative dimensions",finding="completeness and delivery investigation are the clearest P1 actions",decision="sequence management attention",level="LEVEL 2",pbi="yes",readme="yes")
    scope=[100,8,0.327,13.59,95.83]; conf=[3,2,2,2,3]; labels=root.decision_id.tolist(); fig,ax=plt.subplots(figsize=(7.4,5)); ax.scatter(conf,scope,s=[150,120,120,160,180],c=colors,alpha=.85,edgecolor="white"); [ax.text(c+.03,sc,l,fontsize=8) for c,sc,l in zip(conf,scope,labels)]; ax.set_xticks([2,3],["Medium","High"]); ax.set_xlabel("Evidence confidence"); ax.set_ylabel("Scope indicator (displayed label; not common units)"); title(ax,"Business scope and confidence should be viewed together","Scope labels remain in native units in the decision register"); finish(fig,"10_decision_layer/dec_02_scope_vs_confidence.png"); meta("DEC_02","10_decision_layer/dec_02_scope_vs_confidence.png","decision_layer","Which decisions deserve management attention first?","scope vs confidence","decision-card scope","five reviewed decisions","bubble matrix","qualitative confidence labels",finding="large scope does not erase evidence limitations",decision="management attention sequencing",level="LEVEL 2")
    fig,ax=plt.subplots(figsize=(8,4.8)); ax.axis("off"); tree=[("D01","Period completeness","period completeness","no complete period suppressed"),("D02","Acquisition governance","conversion + downstream value","M3 retention"),("D03","Seller onboarding","30/60d activation","M3 retention + value"),("D04","Concentration monitoring","top 1/5/10/20 share","category breadth"),("D05","Delivery investigation","late rate","review / cost")];
    for i,(did,prob,primary,guard) in enumerate(tree): y=0.9-i*.18; ax.text(.02,y,did,weight="bold",color=NAVY); ax.text(.14,y,prob,weight="bold",color=NAVY); ax.text(.52,y,"→  "+primary,color=TEAL); ax.text(.8,y,"→  "+guard,color=RED); ax.plot([.13,.98],[y-.035,y-.035],color="#e5ebf2",lw=.8)
    title(ax,"Decision KPI tree: primary KPI → guardrail"); finish(fig,"10_decision_layer/dec_03_decision_kpi_tree.png"); meta("DEC_03","10_decision_layer/dec_03_decision_kpi_tree.png","decision_layer","What KPI and guardrail govern each action?","decision → primary KPI → guardrail","five decision cards","decision register complete","decision tree","decision-card review",finding="every action has a monitoring path",decision="operating cadence",level="LEVEL 2")
    risk=pd.DataFrame({"decision":root.decision_id,"selection bias":[1,2,2,1,2],"censoring":[2,1,2,1,1],"small sample":[1,2,2,1,1],"causal limitation":[1,3,3,3,3],"measurement limitation":[3,1,2,2,2]}); fig,ax=plt.subplots(figsize=(8,4.8)); sns.heatmap(risk.set_index("decision"),annot=True,cmap="YlOrRd",vmin=0,vmax=3,cbar_kws={"label":"limitation intensity"},ax=ax); title(ax,"Risk and limitation matrix keeps decision boundaries visible"); finish(fig,"10_decision_layer/dec_04_risk_limitation_matrix.png"); meta("DEC_04","10_decision_layer/dec_04_risk_limitation_matrix.png","decision_layer","What limitations constrain each decision?","limitation intensity by decision","five decision cards","reviewed limitation taxonomy","heatmap","qualitative limitation register",finding="causal limitation remains material for observational actions",decision="set stop/escalation rules",level="LEVEL 2")


def main():
    d,detail,seller_order,item_cat,s,activation,retention,conc,exp,health=load_all(); render(d,detail,seller_order,item_cat,s,activation,retention,conc,exp,health)
    pd.DataFrame(REGISTRY).drop_duplicates(subset=["chart_id","chart_file"], keep="first").to_csv(PROJECT/"reports"/"chart_registry.csv",index=False,encoding="utf-8")
    print({"charts":len(REGISTRY),"png_files":len(list(CHART_ROOT.rglob("*.png"))),"registry":str(PROJECT/"reports"/"chart_registry.csv")})


if __name__ == "__main__": main()
