table Category
	lineageTag: 9579fd4a-8955-5e0b-bc79-38e7b692047a

	column purchase_month
		dataType: string
		lineageTag: 1a3891aa-7465-540f-ac2a-8a86f7b6d13d
		summarizeBy: none
		sourceColumn: purchase_month

	column product_category_name_english
		dataType: string
		lineageTag: 18023a7a-347b-5971-a8a0-9adea7de1afa
		summarizeBy: none
		sourceColumn: product_category_name_english

	column gmv_proxy
		dataType: double
		formatString: R$ #,0.00
		lineageTag: 36a4cee5-7036-51e9-997b-221c39e3f991
		summarizeBy: sum
		sourceColumn: gmv_proxy

	column orders
		dataType: int64
		formatString: #,0
		lineageTag: a7490905-67a9-5481-958e-9c5f1e70c6b5
		summarizeBy: sum
		sourceColumn: orders

	column active_sellers
		dataType: int64
		formatString: #,0
		lineageTag: b658dd9c-9ad4-5bfb-b06e-ec0323cf2da8
		summarizeBy: sum
		sourceColumn: active_sellers

	column avg_review_score
		dataType: double
		formatString: 0.0
		lineageTag: fdb96309-4d6f-5156-838b-f5b67125d4e8
		summarizeBy: sum
		sourceColumn: avg_review_score

	column gmv_share_month
		dataType: double
		formatString: 0.0%
		lineageTag: ad44c13a-ba9b-5143-ac87-30e6adfd05c2
		summarizeBy: sum
		sourceColumn: gmv_share_month

	partition Category = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataRoot & "\\reports\\tables\\mart_category_performance.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"purchase_month", type text}, {"product_category_name_english", type text}, {"gmv_proxy", type number}, {"orders", Int64.Type}, {"active_sellers", Int64.Type}, {"avg_review_score", type number}, {"gmv_share_month", type number}}, "en-US"),
				    CSource = Csv.Document(File.Contents(DataRoot & "\\reports\\qa\\period_completeness.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    CPromoted = Table.PromoteHeaders(CSource, [PromoteAllScalars=true]),
				    CTyped = Table.TransformColumnTypes(CPromoted, {{"month", type text}, {"is_executive_complete", type logical}}, "en-US"),
				    Complete = Table.SelectRows(CTyped, each [is_executive_complete] = true),
				    LatestMonth = List.Max(Complete[month]),
				    Latest = Table.SelectRows(Typed, each [purchase_month] = LatestMonth),
				    Sorted = Table.Sort(Latest, {{"gmv_proxy", Order.Descending}}),
				    Top = Typed
				in
				    Top

	annotation PBI_ResultType = Table

