table ConcentrationStats
	lineageTag: 1d81f9d2-b5ae-58e0-b43c-a8edaca003bf

	column metric
		dataType: string
		lineageTag: 14286b70-ba9b-5ed3-b660-2812a912cd1b
		summarizeBy: none
		sourceColumn: metric

	column value
		dataType: double
		formatString: 0.0%
		lineageTag: a8cc09f0-4c11-5f56-9e4c-bb742d29112d
		summarizeBy: sum
		sourceColumn: value

	column unit
		dataType: string
		lineageTag: 603b0570-744e-567d-b253-3d133c2f4a5f
		summarizeBy: none
		sourceColumn: unit

	column population
		dataType: string
		lineageTag: 9721099c-1243-5d5c-970c-fb16b51d6d58
		summarizeBy: none
		sourceColumn: population

	partition ConcentrationStats = m
		mode: import
		source =
				let
				Source = Csv.Document(File.Contents(DataRoot & "\\reports\\statistics\\concentration_statistics.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				Typed = Table.TransformColumnTypes(Promoted, {{"metric", type text}, {"value", type number}, {"unit", type text}, {"population", type text}}, "en-US")
				in
				Typed

	annotation PBI_ResultType = Table

