table CustomerExperience
	lineageTag: 42aad6f1-c9c8-4fa6-bed4-68ff0ccf0385

	measure 'CX Late Delivery Rate' = MAX ( CustomerExperience[SummaryLateRate] )
		formatString: 0.0%
		lineageTag: f74371fe-9b1c-4023-ad18-dce56d98cf70

	measure 'CX Average Review' = MAX ( CustomerExperience[SummaryAvgReview] )
		formatString: 0.00
		lineageTag: 21249b42-53d3-47bd-ada0-df9205ed918a

	measure 'CX Low Review Rate' = MAX ( CustomerExperience[SummaryLowReviewRate] )
		formatString: 0.0%
		lineageTag: 6e5d52d4-c913-43d1-8928-8c9e82aefc5b

	measure 'CX Review Gap' = VAR OnTimeReview = CALCULATE ( MAX ( CustomerExperience[AvgReview] ), CustomerExperience[Segment] = "On Time" ) VAR LateReview = CALCULATE ( MAX ( CustomerExperience[AvgReview] ), CustomerExperience[Segment] = "Late" ) RETURN OnTimeReview - LateReview
		formatString: 0.00
		lineageTag: 1ff7b6c1-1704-4d0b-8894-0f788726eb6d

	measure 'CX Late Delivery Delay Days' = CALCULATE ( MAX ( CustomerExperience[AverageScheduleGapDays] ), CustomerExperience[Segment] = "Late" )
		formatString: 0.0
		lineageTag: 3cfb2673-295d-4112-b5c1-b05f5e2d5536

	measure 'CX Late Rate Delta Label' = VAR Complete = FILTER ( ALL ( Monthly ), Monthly[is_executive_complete] = TRUE () ) VAR LatestMonth = MAXX ( Complete, Monthly[purchase_month] ) VAR PriorMonth = MAXX ( FILTER ( Complete, Monthly[purchase_month] < LatestMonth ), Monthly[purchase_month] ) VAR Delta = ( MAXX ( FILTER ( Complete, Monthly[purchase_month] = LatestMonth ), Monthly[late_delivery_rate] ) - MAXX ( FILTER ( Complete, Monthly[purchase_month] = PriorMonth ), Monthly[late_delivery_rate] ) ) * 100 RETURN IF ( Delta <= 0, "▼ ", "▲ " ) & FORMAT ( Delta, "+0.0;-0.0;0.0" ) & " pp vs prior month"
		formatString: General
		lineageTag: 5f1a0e21-36f0-4d1f-9b08-1d0ad2b4f301

	measure 'CX Review Delta Label' = VAR Complete = FILTER ( ALL ( Monthly ), Monthly[is_executive_complete] = TRUE () ) VAR LatestMonth = MAXX ( Complete, Monthly[purchase_month] ) VAR PriorMonth = MAXX ( FILTER ( Complete, Monthly[purchase_month] < LatestMonth ), Monthly[purchase_month] ) VAR Delta = MAXX ( FILTER ( Complete, Monthly[purchase_month] = LatestMonth ), Monthly[avg_review_score] ) - MAXX ( FILTER ( Complete, Monthly[purchase_month] = PriorMonth ), Monthly[avg_review_score] ) RETURN IF ( Delta >= 0, "▲ ", "▼ " ) & FORMAT ( Delta, "+0.00;-0.00;0.00" ) & " vs prior month"
		formatString: General
		lineageTag: 6a2b1f32-47f1-4e20-ac19-2e1be3c5f402

	measure 'CX Low Review Delta Label' = VAR Complete = FILTER ( ALL ( Monthly ), Monthly[is_executive_complete] = TRUE () ) VAR LatestMonth = MAXX ( Complete, Monthly[purchase_month] ) VAR PriorMonth = MAXX ( FILTER ( Complete, Monthly[purchase_month] < LatestMonth ), Monthly[purchase_month] ) VAR Delta = ( MAXX ( FILTER ( Complete, Monthly[purchase_month] = LatestMonth ), Monthly[low_review_rate] ) - MAXX ( FILTER ( Complete, Monthly[purchase_month] = PriorMonth ), Monthly[low_review_rate] ) ) * 100 RETURN IF ( Delta <= 0, "▼ ", "▲ " ) & FORMAT ( Delta, "+0.0;-0.0;0.0" ) & " pp vs prior month"
		formatString: General
		lineageTag: 7b3c2043-58a2-4f31-bd2a-3f2cf4d60503

	measure 'CX Review Gap Delta Label' = "• Late reviews are " & FORMAT ( [CX Review Gap], "0.00" ) & " points lower"
		formatString: General
		lineageTag: 8c4d3154-69b3-4042-ce3b-4a3da5e71604

	measure 'CX Late Delay Delta Label' = "• Late orders average " & FORMAT ( [CX Late Delivery Delay Days], "0.0" ) & " days late"
		formatString: General
		lineageTag: 9d5e4265-70c4-4153-df4c-5a4ea6f82705

	column Segment
		dataType: string
		lineageTag: a9de3772-dd58-4ac0-bd7e-cd9678a06615
		summarizeBy: none
		sourceColumn: Segment

	column Orders
		dataType: int64
		lineageTag: 95ce2480-64d1-4df8-be16-db98b206c8ba
		summarizeBy: sum
		sourceColumn: Orders

	column LateRate
		dataType: double
		formatString: 0.0%
		lineageTag: 328e649d-9dc3-432e-acc2-9ade804344bc
		summarizeBy: average
		sourceColumn: LateRate

	column AvgReview
		dataType: double
		formatString: 0.00
		lineageTag: be7ce171-1d75-460d-848b-913004484f04
		summarizeBy: average
		sourceColumn: AvgReview

	column LowReviewRate
		dataType: double
		formatString: 0.0%
		lineageTag: 3dea60ce-6407-449b-b916-1dad52eca36e
		summarizeBy: average
		sourceColumn: LowReviewRate

	column AverageScheduleGapDays
		dataType: double
		formatString: 0.0
		lineageTag: 612ee249-de7a-4eef-a4ee-e8f383a2e30c
		summarizeBy: average
		sourceColumn: AverageScheduleGapDays

	column SummaryLateRate
		dataType: double
		formatString: 0.0%
		lineageTag: 7f1f4b74-4b6e-4e90-9d3f-9a7d8c6e2a01
		summarizeBy: max
		sourceColumn: SummaryLateRate

	column SummaryAvgReview
		dataType: double
		formatString: 0.00
		lineageTag: 2a4dfd30-0e31-4b7b-bc73-6a7af1af7e02
		summarizeBy: max
		sourceColumn: SummaryAvgReview

	column SummaryLowReviewRate
		dataType: double
		formatString: 0.0%
		lineageTag: 9b2bdc15-3a2c-47ed-8d2b-2b8f3a9f2b03
		summarizeBy: max
		sourceColumn: SummaryLowReviewRate

	annotation PBI_ResultType = Table

	partition CustomerExperience = m
		mode: import
		source = let Source = Csv.Document(File.Contents(DataRoot & "\\reports\\tables\\powerbi_customer_experience.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]), Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]), Typed = Table.TransformColumnTypes(Headers, {{"Segment", type text}, {"Orders", Int64.Type}, {"LateRate", type number}, {"AvgReview", type number}, {"LowReviewRate", type number}, {"AverageScheduleGapDays", type number}, {"SummaryLateRate", type number}, {"SummaryAvgReview", type number}, {"SummaryLowReviewRate", type number}}, "en-US") in Typed

