table DecisionMatrix
	lineageTag: 9f52f3ab-3b2c-4a4b-9c7a-4c38e1b7d1aa

	column Action
		dataType: string
		lineageTag: 6d7f0c11-8b02-4d0c-8f8a-1e8ec9e9f001
		summarizeBy: none
		sourceColumn: Action

	column Pillar
		dataType: string
		lineageTag: 6d7f0c11-8b02-4d0c-8f8a-1e8ec9e9f002
		summarizeBy: none
		sourceColumn: Pillar

	column Priority
		dataType: string
		lineageTag: 6d7f0c11-8b02-4d0c-8f8a-1e8ec9e9f003
		summarizeBy: none
		sourceColumn: Priority

	column ExpectedImpact
		dataType: int64
		lineageTag: 6d7f0c11-8b02-4d0c-8f8a-1e8ec9e9f004
		summarizeBy: sum
		sourceColumn: ExpectedImpact

	column Effort
		dataType: int64
		lineageTag: 6d7f0c11-8b02-4d0c-8f8a-1e8ec9e9f005
		summarizeBy: sum
		sourceColumn: Effort

	column Owner
		dataType: string
		lineageTag: 6d7f0c11-8b02-4d0c-8f8a-1e8ec9e9f006
		summarizeBy: none
		sourceColumn: Owner

	column TimeHorizon
		dataType: string
		lineageTag: 6d7f0c11-8b02-4d0c-8f8a-1e8ec9e9f007
		summarizeBy: none
		sourceColumn: TimeHorizon

	column Status
		dataType: string
		lineageTag: 6d7f0c11-8b02-4d0c-8f8a-1e8ec9e9f008
		summarizeBy: none
		sourceColumn: Status

	annotation PBI_ResultType = Table

	partition DecisionMatrix = m
		mode: import
		source = let Source = Csv.Document(File.Contents(DataRoot & "\\reports\\tables\\powerbi_decision_matrix_plot.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]), Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]), Typed = Table.TransformColumnTypes(Headers, {{"Action", type text}, {"Pillar", type text}, {"Priority", type text}, {"ExpectedImpact", Int64.Type}, {"Effort", Int64.Type}, {"Owner", type text}, {"TimeHorizon", type text}, {"Status", type text}}, "en-US") in Typed

