table Insights
	lineageTag: 05c4277a-892b-573a-87b6-69c6150672ea

	column Rank
		dataType: int64
		lineageTag: 6dff63e3-8a85-5660-87ac-18569d22e7d1
		summarizeBy: none
		sourceColumn: Rank

	column Headline
		dataType: string
		lineageTag: 957b18fa-97a7-530f-b68e-70331727f993
		summarizeBy: none
		sourceColumn: Headline

	column Detail
		dataType: string
		lineageTag: cdf8abb4-313a-5a93-90b2-79c4545d13a1
		summarizeBy: none
		sourceColumn: Detail

	partition Insights = m
		mode: import
		source = let Source = Csv.Document(File.Contents(DataRoot & "\\reports\\tables\\powerbi_insights.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]), Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]), Typed = Table.TransformColumnTypes(Headers, {{"Rank", Int64.Type}, {"Headline", type text}, {"Detail", type text}}, "en-US") in Typed

	annotation PBI_ResultType = Table

