table RootCauseRegister
	lineageTag: 8b558f6b-9456-4c77-ad2d-e8c3fe41d02e

	measure 'Root Cases' = COUNTROWS ( RootCauseRegister )
		formatString: #,0
		lineageTag: 1a2b3c4d-5e6f-7081-92a3-b4c5d6e7f801

	measure 'Root Hypotheses Tested' = SUM ( RootCauseRegister[HypothesesTested] )
		formatString: #,0
		lineageTag: 2b3c4d5e-6f70-8192-a3b4-c5d6e7f80192

	measure 'Root Supported Signals' = SUM ( RootCauseRegister[SupportedHypotheses] )
		formatString: #,0
		lineageTag: 3c4d5e6f-7081-92a3-b4c5-d6e7f80192a3

	measure 'Root Actionable Cases' = COUNTROWS ( FILTER ( RootCauseRegister, RootCauseRegister[Actionability] <> "Diagnostic drilldown" ) )
		formatString: #,0
		lineageTag: 4d5e6f70-8192-a3b4-c5d6-e7f80192a3b4

	measure 'Root Inconclusive Paths' = SUM ( RootCauseRegister[InconclusiveHypotheses] )
		formatString: #,0
		lineageTag: 5e6f7081-92a3-b4c5-d6e7-f80192a3b4c5

	measure 'Root Cases Delta Label' = "• " & FORMAT ( [Root Cases], "0" ) & " governed cases"
		formatString: General
		lineageTag: 6f708192-a3b4-c5d6-e7f8-0192a3b4c5d6

	measure 'Root Hypotheses Delta Label' = "• " & FORMAT ( [Root Hypotheses Tested], "0" ) & " hypotheses assessed"
		formatString: General
		lineageTag: 708192a3-b4c5-d6e7-f801-92a3b4c5d6e7

	measure 'Root Supported Delta Label' = "• " & FORMAT ( [Root Supported Signals], "0" ) & " supported signals"
		formatString: General
		lineageTag: 8192a3b4-c5d6-e7f8-0192-a3b4c5d6e7f8

	measure 'Root Actionable Delta Label' = "• " & FORMAT ( [Root Actionable Cases], "0" ) & " cases have an action path"
		formatString: General
		lineageTag: 92a3b4c5-d6e7-f801-92a3-b4c5d6e7f801

	measure 'Root Inconclusive Delta Label' = "• " & FORMAT ( [Root Inconclusive Paths], "0" ) & " paths remain inconclusive"
		formatString: General
		lineageTag: a3b4c5d6-e7f8-0192-a3b4-c5d6e7f80192

	column Case
		dataType: string
		lineageTag: 0f6d0743-bc23-41b1-a94f-4248c769c588
		summarizeBy: none
		sourceColumn: Case

	column Driver
		dataType: string
		lineageTag: 1f7e1854-cd34-52c2-b05f-5359d87a69d9
		summarizeBy: none
		sourceColumn: Driver

	column EvidenceStatus
		dataType: string
		lineageTag: 2f8f2965-de45-63d3-c160-646ae98b7aea
		summarizeBy: none
		sourceColumn: EvidenceStatus

	column HypothesesTested
		dataType: int64
		lineageTag: 3f904a76-ef56-74e4-d271-757bfa9c8bfb
		summarizeBy: sum
		sourceColumn: HypothesesTested

	column SupportedHypotheses
		dataType: int64
		lineageTag: 40a15b87-f067-85f5-e382-868cfbad9c0c
		summarizeBy: sum
		sourceColumn: SupportedHypotheses

	column PlausibleHypotheses
		dataType: int64
		lineageTag: 51b26c98-0178-96a6-f493-979d0cbead1d
		summarizeBy: sum
		sourceColumn: PlausibleHypotheses

	column RejectedHypotheses
		dataType: int64
		lineageTag: 62c37da9-1289-a7b7-05a4-a8ae1dcfbe2e
		summarizeBy: sum
		sourceColumn: RejectedHypotheses

	column InconclusiveHypotheses
		dataType: int64
		lineageTag: 73d48eba-239a-b8c8-16b5-b9bf2ed0cf3f
		summarizeBy: sum
		sourceColumn: InconclusiveHypotheses

	column Actionability
		dataType: string
		lineageTag: 84e59fcb-34ac-c9d9-27c6-cac03fe1d040
		summarizeBy: none
		sourceColumn: Actionability

	column Owner
		dataType: string
		lineageTag: 4c1d7e9a-8f30-4b2e-a6d5-3e1c9b7f4a62
		summarizeBy: none
		sourceColumn: Owner

	partition RootCauseRegister = m
		mode: import
		source = let Source = Csv.Document(File.Contents(DataRoot & "\\reports\\tables\\powerbi_root_cause_register.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]), Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]), Typed = Table.TransformColumnTypes(Headers, {{"Case", type text}, {"Driver", type text}, {"EvidenceStatus", type text}, {"HypothesesTested", Int64.Type}, {"SupportedHypotheses", Int64.Type}, {"PlausibleHypotheses", Int64.Type}, {"RejectedHypotheses", Int64.Type}, {"InconclusiveHypotheses", Int64.Type}, {"Actionability", type text}, {"Owner", type text}}, "en-US") in Typed
